/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import javax.swing.JPanel;

/**
 *
 * @author user
 */
public class Dashbord extends javax.swing.JFrame {

    /**
     * Creates new form Dashbord
     */
    

    public Dashbord() {
        initComponents();
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplayPink.png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));
       
       
        
    }
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frame_logo_toko = new javax.swing.JPanel();
        navigasi_panel = new javax.swing.JPanel();
        panel_dashbord = new javax.swing.JPanel();
        icon_dashbord = new javax.swing.JLabel();
        panel_product = new javax.swing.JPanel();
        icon_product = new javax.swing.JLabel();
        panel_kasir = new javax.swing.JPanel();
        icon_kasir = new javax.swing.JLabel();
        panel_manager = new javax.swing.JPanel();
        icon_manager = new javax.swing.JLabel();
        panel_laporan = new javax.swing.JPanel();
        icon_laporan = new javax.swing.JLabel();
        panel_setting = new javax.swing.JPanel();
        icon_setting = new javax.swing.JLabel();
        ConntainerPanel = new javax.swing.JPanel();
        panel_contenDashbord = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panel_contenBarang = new javax.swing.JPanel();
        panel_contenKasir = new javax.swing.JPanel();
        panel_contenSetting = new javax.swing.JPanel();
        panel_contenManageUser = new javax.swing.JPanel();
        panel_contenLaporan = new javax.swing.JPanel();
        panel_navigasiLaporan = new RoundedPanel(20, Color.white);
        panel_laporanPenjualan = new javax.swing.JPanel();
        label_laporanPenjualan = new javax.swing.JLabel();
        panel_laporanTransaksi = new javax.swing.JPanel();
        label_laporanTransaksi = new javax.swing.JLabel();
        ContainerPanel_Laporan = new RoundedPanel(20, Color.white);
        ContainerPanel_LaporanTransaksi = new RoundedPanel(20, Color.white);
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_LaporanTransaksi = new javax.swing.JTable();
        ContainerPanel_LaporanPenjualan = new RoundedPanel(20, Color.white);
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_LaporanPenjualan = new javax.swing.JTable();
        header_panel = new RoundedPanel(20, Color.white);
        label_page = new javax.swing.JLabel();
        label_namatoko = new javax.swing.JLabel();
        label_namauser = new javax.swing.JLabel();
        icon_user = new javax.swing.JLabel();
        label_tanggal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        frame_logo_toko.setBackground(new java.awt.Color(255, 255, 255));
        frame_logo_toko.setPreferredSize(new java.awt.Dimension(66, 66));

        javax.swing.GroupLayout frame_logo_tokoLayout = new javax.swing.GroupLayout(frame_logo_toko);
        frame_logo_toko.setLayout(frame_logo_tokoLayout);
        frame_logo_tokoLayout.setHorizontalGroup(
            frame_logo_tokoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        frame_logo_tokoLayout.setVerticalGroup(
            frame_logo_tokoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        navigasi_panel.setBackground(new java.awt.Color(255, 255, 255));

        panel_dashbord.setBackground(new java.awt.Color(255, 255, 255));
        panel_dashbord.setPreferredSize(new java.awt.Dimension(66, 60));
        panel_dashbord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_dashbordMouseClicked(evt);
            }
        });

        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png"))); // NOI18N
        icon_dashbord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_dashbordMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_dashbordLayout = new javax.swing.GroupLayout(panel_dashbord);
        panel_dashbord.setLayout(panel_dashbordLayout);
        panel_dashbordLayout.setHorizontalGroup(
            panel_dashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dashbordLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(icon_dashbord)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panel_dashbordLayout.setVerticalGroup(
            panel_dashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_dashbordLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(icon_dashbord)
                .addGap(19, 19, 19))
        );

        panel_product.setBackground(new java.awt.Color(255, 255, 255));
        panel_product.setPreferredSize(new java.awt.Dimension(66, 60));
        panel_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_productMouseClicked(evt);
            }
        });

        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png"))); // NOI18N
        icon_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_productMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_productLayout = new javax.swing.GroupLayout(panel_product);
        panel_product.setLayout(panel_productLayout);
        panel_productLayout.setHorizontalGroup(
            panel_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_productLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(icon_product)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_productLayout.setVerticalGroup(
            panel_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_productLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(icon_product)
                .addGap(19, 19, 19))
        );

        panel_kasir.setBackground(new java.awt.Color(255, 255, 255));
        panel_kasir.setPreferredSize(new java.awt.Dimension(66, 60));
        panel_kasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_kasirMouseClicked(evt);
            }
        });

        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png"))); // NOI18N
        icon_kasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_kasirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_kasirLayout = new javax.swing.GroupLayout(panel_kasir);
        panel_kasir.setLayout(panel_kasirLayout);
        panel_kasirLayout.setHorizontalGroup(
            panel_kasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_kasirLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(icon_kasir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_kasirLayout.setVerticalGroup(
            panel_kasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_kasirLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(icon_kasir)
                .addGap(19, 19, 19))
        );

        panel_manager.setBackground(new java.awt.Color(255, 255, 255));
        panel_manager.setPreferredSize(new java.awt.Dimension(66, 60));
        panel_manager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_managerMouseClicked(evt);
            }
        });

        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png"))); // NOI18N
        icon_manager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_managerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icon_managerMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panel_managerLayout = new javax.swing.GroupLayout(panel_manager);
        panel_manager.setLayout(panel_managerLayout);
        panel_managerLayout.setHorizontalGroup(
            panel_managerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_managerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(icon_manager)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panel_managerLayout.setVerticalGroup(
            panel_managerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_managerLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(icon_manager)
                .addGap(19, 19, 19))
        );

        panel_laporan.setBackground(new java.awt.Color(255, 255, 255));
        panel_laporan.setPreferredSize(new java.awt.Dimension(66, 60));
        panel_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_laporanMouseClicked(evt);
            }
        });

        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png"))); // NOI18N
        icon_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_laporanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_laporanLayout = new javax.swing.GroupLayout(panel_laporan);
        panel_laporan.setLayout(panel_laporanLayout);
        panel_laporanLayout.setHorizontalGroup(
            panel_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_laporanLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(icon_laporan)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panel_laporanLayout.setVerticalGroup(
            panel_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_laporanLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(icon_laporan)
                .addGap(19, 19, 19))
        );

        panel_setting.setBackground(new java.awt.Color(255, 255, 255));
        panel_setting.setPreferredSize(new java.awt.Dimension(66, 60));
        panel_setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_settingMouseClicked(evt);
            }
        });

        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png"))); // NOI18N
        icon_setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_settingMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_settingLayout = new javax.swing.GroupLayout(panel_setting);
        panel_setting.setLayout(panel_settingLayout);
        panel_settingLayout.setHorizontalGroup(
            panel_settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_settingLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(icon_setting)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panel_settingLayout.setVerticalGroup(
            panel_settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_settingLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(icon_setting)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout navigasi_panelLayout = new javax.swing.GroupLayout(navigasi_panel);
        navigasi_panel.setLayout(navigasi_panelLayout);
        navigasi_panelLayout.setHorizontalGroup(
            navigasi_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_kasir, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
            .addComponent(panel_product, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
            .addComponent(panel_dashbord, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panel_manager, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panel_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panel_setting, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        navigasi_panelLayout.setVerticalGroup(
            navigasi_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigasi_panelLayout.createSequentialGroup()
                .addComponent(panel_dashbord, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_kasir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_product, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_manager, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_setting, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ConntainerPanel.setLayout(new java.awt.CardLayout());

        panel_contenDashbord.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_contenDashbordLayout = new javax.swing.GroupLayout(panel_contenDashbord);
        panel_contenDashbord.setLayout(panel_contenDashbordLayout);
        panel_contenDashbordLayout.setHorizontalGroup(
            panel_contenDashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_contenDashbordLayout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(857, Short.MAX_VALUE))
        );
        panel_contenDashbordLayout.setVerticalGroup(
            panel_contenDashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_contenDashbordLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(465, Short.MAX_VALUE))
        );

        ConntainerPanel.add(panel_contenDashbord, "card13");

        panel_contenBarang.setBackground(new java.awt.Color(102, 102, 255));
        panel_contenBarang.setForeground(new java.awt.Color(153, 102, 255));

        javax.swing.GroupLayout panel_contenBarangLayout = new javax.swing.GroupLayout(panel_contenBarang);
        panel_contenBarang.setLayout(panel_contenBarangLayout);
        panel_contenBarangLayout.setHorizontalGroup(
            panel_contenBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1281, Short.MAX_VALUE)
        );
        panel_contenBarangLayout.setVerticalGroup(
            panel_contenBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );

        ConntainerPanel.add(panel_contenBarang, "card8");

        panel_contenKasir.setBackground(new java.awt.Color(51, 255, 153));

        javax.swing.GroupLayout panel_contenKasirLayout = new javax.swing.GroupLayout(panel_contenKasir);
        panel_contenKasir.setLayout(panel_contenKasirLayout);
        panel_contenKasirLayout.setHorizontalGroup(
            panel_contenKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1281, Short.MAX_VALUE)
        );
        panel_contenKasirLayout.setVerticalGroup(
            panel_contenKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );

        ConntainerPanel.add(panel_contenKasir, "card9");

        panel_contenSetting.setBackground(new java.awt.Color(51, 153, 0));

        javax.swing.GroupLayout panel_contenSettingLayout = new javax.swing.GroupLayout(panel_contenSetting);
        panel_contenSetting.setLayout(panel_contenSettingLayout);
        panel_contenSettingLayout.setHorizontalGroup(
            panel_contenSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1281, Short.MAX_VALUE)
        );
        panel_contenSettingLayout.setVerticalGroup(
            panel_contenSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );

        ConntainerPanel.add(panel_contenSetting, "card10");

        panel_contenManageUser.setBackground(new java.awt.Color(153, 0, 204));

        javax.swing.GroupLayout panel_contenManageUserLayout = new javax.swing.GroupLayout(panel_contenManageUser);
        panel_contenManageUser.setLayout(panel_contenManageUserLayout);
        panel_contenManageUserLayout.setHorizontalGroup(
            panel_contenManageUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1281, Short.MAX_VALUE)
        );
        panel_contenManageUserLayout.setVerticalGroup(
            panel_contenManageUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );

        ConntainerPanel.add(panel_contenManageUser, "card11");

        panel_contenLaporan.setPreferredSize(new java.awt.Dimension(1281, 663));

        panel_navigasiLaporan.setPreferredSize(new java.awt.Dimension(470, 100));

        panel_laporanPenjualan.setBackground(new java.awt.Color(255, 255, 255));
        panel_laporanPenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_laporanPenjualanMouseClicked(evt);
            }
        });

        label_laporanPenjualan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_laporanPenjualan.setText("Laporan Penjualan");

        javax.swing.GroupLayout panel_laporanPenjualanLayout = new javax.swing.GroupLayout(panel_laporanPenjualan);
        panel_laporanPenjualan.setLayout(panel_laporanPenjualanLayout);
        panel_laporanPenjualanLayout.setHorizontalGroup(
            panel_laporanPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_laporanPenjualanLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(label_laporanPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        panel_laporanPenjualanLayout.setVerticalGroup(
            panel_laporanPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_laporanPenjualanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_laporanPenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel_laporanTransaksi.setBackground(new java.awt.Color(255, 255, 255));
        panel_laporanTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_laporanTransaksiMouseClicked(evt);
            }
        });

        label_laporanTransaksi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_laporanTransaksi.setForeground(new java.awt.Color(252, 164, 164));
        label_laporanTransaksi.setText("Laporan Trasaksi");

        javax.swing.GroupLayout panel_laporanTransaksiLayout = new javax.swing.GroupLayout(panel_laporanTransaksi);
        panel_laporanTransaksi.setLayout(panel_laporanTransaksiLayout);
        panel_laporanTransaksiLayout.setHorizontalGroup(
            panel_laporanTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_laporanTransaksiLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(label_laporanTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        panel_laporanTransaksiLayout.setVerticalGroup(
            panel_laporanTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_laporanTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_laporanTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_navigasiLaporanLayout = new javax.swing.GroupLayout(panel_navigasiLaporan);
        panel_navigasiLaporan.setLayout(panel_navigasiLaporanLayout);
        panel_navigasiLaporanLayout.setHorizontalGroup(
            panel_navigasiLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_navigasiLaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_laporanTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(panel_laporanPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_navigasiLaporanLayout.setVerticalGroup(
            panel_navigasiLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_navigasiLaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_navigasiLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_laporanTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_laporanPenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        ContainerPanel_Laporan.setLayout(new java.awt.CardLayout());

        Table_LaporanTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No.", "Id Transaksi", "Supplier", "Tanggal Transaksi", "Total Barang", "Total Return", "Total Harga"
            }
        ));
        jScrollPane1.setViewportView(Table_LaporanTransaksi);

        javax.swing.GroupLayout ContainerPanel_LaporanTransaksiLayout = new javax.swing.GroupLayout(ContainerPanel_LaporanTransaksi);
        ContainerPanel_LaporanTransaksi.setLayout(ContainerPanel_LaporanTransaksiLayout);
        ContainerPanel_LaporanTransaksiLayout.setHorizontalGroup(
            ContainerPanel_LaporanTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerPanel_LaporanTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1222, Short.MAX_VALUE)
                .addContainerGap())
        );
        ContainerPanel_LaporanTransaksiLayout.setVerticalGroup(
            ContainerPanel_LaporanTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerPanel_LaporanTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addContainerGap())
        );

        ContainerPanel_Laporan.add(ContainerPanel_LaporanTransaksi, "card2");

        Table_LaporanPenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No.", "Id Transaksi", "Kasir", "Tanggal Transaksi", "Total Barang", "Total Return", "Total Harga"
            }
        ));
        jScrollPane2.setViewportView(Table_LaporanPenjualan);

        javax.swing.GroupLayout ContainerPanel_LaporanPenjualanLayout = new javax.swing.GroupLayout(ContainerPanel_LaporanPenjualan);
        ContainerPanel_LaporanPenjualan.setLayout(ContainerPanel_LaporanPenjualanLayout);
        ContainerPanel_LaporanPenjualanLayout.setHorizontalGroup(
            ContainerPanel_LaporanPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerPanel_LaporanPenjualanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1222, Short.MAX_VALUE)
                .addContainerGap())
        );
        ContainerPanel_LaporanPenjualanLayout.setVerticalGroup(
            ContainerPanel_LaporanPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerPanel_LaporanPenjualanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addContainerGap())
        );

        ContainerPanel_Laporan.add(ContainerPanel_LaporanPenjualan, "card2");

        javax.swing.GroupLayout panel_contenLaporanLayout = new javax.swing.GroupLayout(panel_contenLaporan);
        panel_contenLaporan.setLayout(panel_contenLaporanLayout);
        panel_contenLaporanLayout.setHorizontalGroup(
            panel_contenLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_contenLaporanLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel_contenLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContainerPanel_Laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 1242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_navigasiLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panel_contenLaporanLayout.setVerticalGroup(
            panel_contenLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_contenLaporanLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panel_navigasiLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(ContainerPanel_Laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        ConntainerPanel.add(panel_contenLaporan, "card12");

        label_page.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        label_page.setText("Dashbord");

        label_namatoko.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label_namatoko.setText("BANAJ MOSLEM FRAGRANCE");

        label_namauser.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        label_namauser.setText("Tegar");

        icon_user.setText("Icon");

        label_tanggal.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        label_tanggal.setText("20-Agustus-2020");

        javax.swing.GroupLayout header_panelLayout = new javax.swing.GroupLayout(header_panel);
        header_panel.setLayout(header_panelLayout);
        header_panelLayout.setHorizontalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_panelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_page)
                    .addComponent(label_namatoko))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 748, Short.MAX_VALUE)
                .addGroup(header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_panelLayout.createSequentialGroup()
                        .addComponent(icon_user)
                        .addGap(49, 49, 49)
                        .addComponent(label_namauser))
                    .addComponent(label_tanggal, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(10, 10, 10))
        );
        header_panelLayout.setVerticalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_page)
                .addGap(10, 10, 10)
                .addComponent(label_namatoko)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_namauser)
                    .addComponent(icon_user))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_tanggal)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(navigasi_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(frame_logo_toko, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConntainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(header_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(header_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConntainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(frame_logo_toko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(navigasi_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void icon_dashbordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_dashbordMouseClicked
        // TODO add your handling code here:
        
        ConntainerPanel.removeAll();
        ConntainerPanel.add(panel_contenDashbord);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
        
        //visibilitas
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplayPink.png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));
        
    }//GEN-LAST:event_icon_dashbordMouseClicked

    private void icon_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_productMouseClicked
        // TODO add your handling code here:
        ConntainerPanel.removeAll();
        ConntainerPanel.add(panel_contenBarang);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
        
        //visibilitas icon
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfumePink.png")));
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));
        
        
    }//GEN-LAST:event_icon_productMouseClicked

    private void icon_managerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_managerMouseClicked
         // TODO add your handling code here:
          ConntainerPanel.removeAll();
        ConntainerPanel.add(panel_contenManageUser);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
        //visibilitas icon
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/manager (1).png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
        
        
    }//GEN-LAST:event_icon_managerMouseClicked

    private void icon_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_laporanMouseClicked
        // TODO add your handling code here:
        ConntainerPanel.removeAll();
        ConntainerPanel.add(panel_contenLaporan);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
        
        //visibilitas icon
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulsePink.png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
    }//GEN-LAST:event_icon_laporanMouseClicked

    private void icon_kasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_kasirMouseClicked
         // TODO add your handling code here:
        ConntainerPanel.removeAll();
        ConntainerPanel.add(panel_contenKasir);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
        
        //visibilitas icon
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cartPink.png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
        
        
        
    }//GEN-LAST:event_icon_kasirMouseClicked

    private void icon_settingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_settingMouseClicked

         // TODO add your handling code here:\
        
        ConntainerPanel.removeAll();
        ConntainerPanel.add(panel_contenSetting);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
        
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingPink.png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));


         

    }//GEN-LAST:event_icon_settingMouseClicked

    private void panel_managerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_managerMouseClicked
        // TODO add your handling code here:
        
        ConntainerPanel.removeAll();
        ConntainerPanel.add(panel_contenManageUser);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
        
        
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/manager (1).png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
        
    }//GEN-LAST:event_panel_managerMouseClicked

    private void panel_dashbordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_dashbordMouseClicked
        // TODO add your handling code here:
        
        ConntainerPanel.removeAll();
        ConntainerPanel.add(panel_contenDashbord);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
        
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplayPink.png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));
    }//GEN-LAST:event_panel_dashbordMouseClicked

    private void panel_kasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_kasirMouseClicked
        // TODO add your handling code here:
        ConntainerPanel.removeAll();
        ConntainerPanel.add(panel_contenKasir);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
        
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cartPink.png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
        
    }//GEN-LAST:event_panel_kasirMouseClicked

    private void panel_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_productMouseClicked
        // TODO add your handling code here:
        ConntainerPanel.removeAll();
        ConntainerPanel.add(panel_contenBarang);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
         //visibilitas icon
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfumePink.png")));
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));
    }//GEN-LAST:event_panel_productMouseClicked

    private void panel_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_laporanMouseClicked
        // TODO add your handling code here:   
          ConntainerPanel.removeAll();
        ConntainerPanel.add(panel_contenLaporan);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
        
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulsePink.png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
        
        
        
    }//GEN-LAST:event_panel_laporanMouseClicked

    private void panel_settingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_settingMouseClicked
        // TODO add your handling code here:
        
        ConntainerPanel.removeAll();
        ConntainerPanel.add(panel_contenSetting);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
        
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingPink.png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));
    }//GEN-LAST:event_panel_settingMouseClicked

    private void icon_managerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_managerMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_icon_managerMouseEntered

    private void panel_laporanTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_laporanTransaksiMouseClicked
        // TODO add your handling code here:
        ContainerPanel_Laporan.removeAll();
        ContainerPanel_Laporan.add(ContainerPanel_LaporanTransaksi);
        ContainerPanel_Laporan.repaint();
        ContainerPanel_Laporan.revalidate();
        
        label_laporanTransaksi.setForeground(new Color(252,164,164));
        label_laporanPenjualan.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_panel_laporanTransaksiMouseClicked

    private void panel_laporanPenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_laporanPenjualanMouseClicked
        // TODO add your handling code here:
        ContainerPanel_Laporan.removeAll();
        ContainerPanel_Laporan.add(ContainerPanel_LaporanPenjualan);
        ContainerPanel_Laporan.repaint();
        ContainerPanel_Laporan.revalidate();
        
        label_laporanPenjualan.setForeground(new Color(252,164,164));
        label_laporanTransaksi.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_panel_laporanPenjualanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashbord().setVisible(true);
            }
        });
    }
    
    class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ConntainerPanel;
    private javax.swing.JPanel ContainerPanel_Laporan;
    private javax.swing.JPanel ContainerPanel_LaporanPenjualan;
    private javax.swing.JPanel ContainerPanel_LaporanTransaksi;
    private javax.swing.JTable Table_LaporanPenjualan;
    private javax.swing.JTable Table_LaporanTransaksi;
    private javax.swing.JPanel frame_logo_toko;
    private javax.swing.JPanel header_panel;
    private javax.swing.JLabel icon_dashbord;
    private javax.swing.JLabel icon_kasir;
    private javax.swing.JLabel icon_laporan;
    private javax.swing.JLabel icon_manager;
    private javax.swing.JLabel icon_product;
    private javax.swing.JLabel icon_setting;
    private javax.swing.JLabel icon_user;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_laporanPenjualan;
    private javax.swing.JLabel label_laporanTransaksi;
    private javax.swing.JLabel label_namatoko;
    private javax.swing.JLabel label_namauser;
    private javax.swing.JLabel label_page;
    private javax.swing.JLabel label_tanggal;
    private javax.swing.JPanel navigasi_panel;
    private javax.swing.JPanel panel_contenBarang;
    private javax.swing.JPanel panel_contenDashbord;
    private javax.swing.JPanel panel_contenKasir;
    private javax.swing.JPanel panel_contenLaporan;
    private javax.swing.JPanel panel_contenManageUser;
    private javax.swing.JPanel panel_contenSetting;
    private javax.swing.JPanel panel_dashbord;
    private javax.swing.JPanel panel_kasir;
    private javax.swing.JPanel panel_laporan;
    private javax.swing.JPanel panel_laporanPenjualan;
    private javax.swing.JPanel panel_laporanTransaksi;
    private javax.swing.JPanel panel_manager;
    private javax.swing.JPanel panel_navigasiLaporan;
    private javax.swing.JPanel panel_product;
    private javax.swing.JPanel panel_setting;
    // End of variables declaration//GEN-END:variables
}
