/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import javax.swing.JPanel;

/**
 *
 * @author user
 */
public class Dashbord extends javax.swing.JFrame {

    /**
     * Creates new form Dashbord
     */
    

    public Dashbord() {
        initComponents();
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplayPink.png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));
       
       
        
    }
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frame_logo_toko = new javax.swing.JPanel();
        navigasi_panel = new javax.swing.JPanel();
        panel_dashbord = new javax.swing.JPanel();
        icon_dashbord = new javax.swing.JLabel();
        panel_dashbord1 = new javax.swing.JPanel();
        icon_product = new javax.swing.JLabel();
        panel_dashbord2 = new javax.swing.JPanel();
        icon_kasir = new javax.swing.JLabel();
        panel_dashbord3 = new javax.swing.JPanel();
        icon_manager = new javax.swing.JLabel();
        panel_dashbord4 = new javax.swing.JPanel();
        icon_laporan = new javax.swing.JLabel();
        panel_dashbord5 = new javax.swing.JPanel();
        icon_setting = new javax.swing.JLabel();
        ConntainerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panel_contenBarang = new javax.swing.JPanel();
        panel_contenKasir = new javax.swing.JPanel();
        panel_contenSetting = new javax.swing.JPanel();
        panel_contenManageUser = new javax.swing.JPanel();
        panel_contenLaporan = new javax.swing.JPanel();
        panel_contenDashbord = new javax.swing.JPanel();
        header_panel = new RoundedPanel(20, Color.white);
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));

        frame_logo_toko.setBackground(new java.awt.Color(255, 255, 255));
        frame_logo_toko.setPreferredSize(new java.awt.Dimension(66, 66));

        javax.swing.GroupLayout frame_logo_tokoLayout = new javax.swing.GroupLayout(frame_logo_toko);
        frame_logo_toko.setLayout(frame_logo_tokoLayout);
        frame_logo_tokoLayout.setHorizontalGroup(
            frame_logo_tokoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        frame_logo_tokoLayout.setVerticalGroup(
            frame_logo_tokoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        navigasi_panel.setBackground(new java.awt.Color(255, 255, 255));

        panel_dashbord.setBackground(new java.awt.Color(255, 255, 255));
        panel_dashbord.setPreferredSize(new java.awt.Dimension(66, 60));
        panel_dashbord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_dashbordMouseClicked(evt);
            }
        });

        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png"))); // NOI18N
        icon_dashbord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_dashbordMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_dashbordLayout = new javax.swing.GroupLayout(panel_dashbord);
        panel_dashbord.setLayout(panel_dashbordLayout);
        panel_dashbordLayout.setHorizontalGroup(
            panel_dashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dashbordLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(icon_dashbord)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panel_dashbordLayout.setVerticalGroup(
            panel_dashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_dashbordLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(icon_dashbord)
                .addGap(19, 19, 19))
        );

        panel_dashbord1.setBackground(new java.awt.Color(255, 255, 255));
        panel_dashbord1.setPreferredSize(new java.awt.Dimension(66, 60));
        panel_dashbord1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_dashbord1MouseClicked(evt);
            }
        });

        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png"))); // NOI18N
        icon_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_productMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_dashbord1Layout = new javax.swing.GroupLayout(panel_dashbord1);
        panel_dashbord1.setLayout(panel_dashbord1Layout);
        panel_dashbord1Layout.setHorizontalGroup(
            panel_dashbord1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dashbord1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(icon_product)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_dashbord1Layout.setVerticalGroup(
            panel_dashbord1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_dashbord1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(icon_product)
                .addGap(19, 19, 19))
        );

        panel_dashbord2.setBackground(new java.awt.Color(255, 255, 255));
        panel_dashbord2.setPreferredSize(new java.awt.Dimension(66, 60));
        panel_dashbord2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_dashbord2MouseClicked(evt);
            }
        });

        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png"))); // NOI18N
        icon_kasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_kasirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_dashbord2Layout = new javax.swing.GroupLayout(panel_dashbord2);
        panel_dashbord2.setLayout(panel_dashbord2Layout);
        panel_dashbord2Layout.setHorizontalGroup(
            panel_dashbord2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dashbord2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(icon_kasir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_dashbord2Layout.setVerticalGroup(
            panel_dashbord2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_dashbord2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(icon_kasir)
                .addGap(19, 19, 19))
        );

        panel_dashbord3.setBackground(new java.awt.Color(255, 255, 255));
        panel_dashbord3.setPreferredSize(new java.awt.Dimension(66, 60));
        panel_dashbord3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_dashbord3MouseClicked(evt);
            }
        });

        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png"))); // NOI18N
        icon_manager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_managerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icon_managerMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panel_dashbord3Layout = new javax.swing.GroupLayout(panel_dashbord3);
        panel_dashbord3.setLayout(panel_dashbord3Layout);
        panel_dashbord3Layout.setHorizontalGroup(
            panel_dashbord3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dashbord3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(icon_manager)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panel_dashbord3Layout.setVerticalGroup(
            panel_dashbord3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_dashbord3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(icon_manager)
                .addGap(19, 19, 19))
        );

        panel_dashbord4.setBackground(new java.awt.Color(255, 255, 255));
        panel_dashbord4.setPreferredSize(new java.awt.Dimension(66, 60));
        panel_dashbord4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_dashbord4MouseClicked(evt);
            }
        });

        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png"))); // NOI18N
        icon_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_laporanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_dashbord4Layout = new javax.swing.GroupLayout(panel_dashbord4);
        panel_dashbord4.setLayout(panel_dashbord4Layout);
        panel_dashbord4Layout.setHorizontalGroup(
            panel_dashbord4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dashbord4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(icon_laporan)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panel_dashbord4Layout.setVerticalGroup(
            panel_dashbord4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_dashbord4Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(icon_laporan)
                .addGap(19, 19, 19))
        );

        panel_dashbord5.setBackground(new java.awt.Color(255, 255, 255));
        panel_dashbord5.setPreferredSize(new java.awt.Dimension(66, 60));
        panel_dashbord5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_dashbord5MouseClicked(evt);
            }
        });

        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png"))); // NOI18N
        icon_setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_settingMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_dashbord5Layout = new javax.swing.GroupLayout(panel_dashbord5);
        panel_dashbord5.setLayout(panel_dashbord5Layout);
        panel_dashbord5Layout.setHorizontalGroup(
            panel_dashbord5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dashbord5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(icon_setting)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panel_dashbord5Layout.setVerticalGroup(
            panel_dashbord5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_dashbord5Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(icon_setting)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout navigasi_panelLayout = new javax.swing.GroupLayout(navigasi_panel);
        navigasi_panel.setLayout(navigasi_panelLayout);
        navigasi_panelLayout.setHorizontalGroup(
            navigasi_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_dashbord2, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
            .addComponent(panel_dashbord1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
            .addComponent(panel_dashbord, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panel_dashbord3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panel_dashbord4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panel_dashbord5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        navigasi_panelLayout.setVerticalGroup(
            navigasi_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigasi_panelLayout.createSequentialGroup()
                .addComponent(panel_dashbord, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_dashbord2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_dashbord1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_dashbord3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_dashbord4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_dashbord5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ConntainerPanel.setLayout(new java.awt.CardLayout());

        jLabel2.setText("anjim");
        ConntainerPanel.add(jLabel2, "card3");

        jLabel3.setText("oke bang");
        ConntainerPanel.add(jLabel3, "card4");

        jLabel4.setText("gabut ya");
        ConntainerPanel.add(jLabel4, "card5");

        jLabel5.setText("jLabel5");
        ConntainerPanel.add(jLabel5, "card6");

        jLabel1.setText("babi");
        ConntainerPanel.add(jLabel1, "card2");

        jLabel11.setText("jLabel11");
        ConntainerPanel.add(jLabel11, "card7");

        panel_contenBarang.setBackground(new java.awt.Color(102, 102, 255));
        panel_contenBarang.setForeground(new java.awt.Color(153, 102, 255));

        javax.swing.GroupLayout panel_contenBarangLayout = new javax.swing.GroupLayout(panel_contenBarang);
        panel_contenBarang.setLayout(panel_contenBarangLayout);
        panel_contenBarangLayout.setHorizontalGroup(
            panel_contenBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1281, Short.MAX_VALUE)
        );
        panel_contenBarangLayout.setVerticalGroup(
            panel_contenBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );

        ConntainerPanel.add(panel_contenBarang, "card8");

        panel_contenKasir.setBackground(new java.awt.Color(51, 255, 153));

        javax.swing.GroupLayout panel_contenKasirLayout = new javax.swing.GroupLayout(panel_contenKasir);
        panel_contenKasir.setLayout(panel_contenKasirLayout);
        panel_contenKasirLayout.setHorizontalGroup(
            panel_contenKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1281, Short.MAX_VALUE)
        );
        panel_contenKasirLayout.setVerticalGroup(
            panel_contenKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );

        ConntainerPanel.add(panel_contenKasir, "card9");

        panel_contenSetting.setBackground(new java.awt.Color(51, 153, 0));

        javax.swing.GroupLayout panel_contenSettingLayout = new javax.swing.GroupLayout(panel_contenSetting);
        panel_contenSetting.setLayout(panel_contenSettingLayout);
        panel_contenSettingLayout.setHorizontalGroup(
            panel_contenSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1281, Short.MAX_VALUE)
        );
        panel_contenSettingLayout.setVerticalGroup(
            panel_contenSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );

        ConntainerPanel.add(panel_contenSetting, "card10");

        panel_contenManageUser.setBackground(new java.awt.Color(153, 0, 204));

        javax.swing.GroupLayout panel_contenManageUserLayout = new javax.swing.GroupLayout(panel_contenManageUser);
        panel_contenManageUser.setLayout(panel_contenManageUserLayout);
        panel_contenManageUserLayout.setHorizontalGroup(
            panel_contenManageUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1281, Short.MAX_VALUE)
        );
        panel_contenManageUserLayout.setVerticalGroup(
            panel_contenManageUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );

        ConntainerPanel.add(panel_contenManageUser, "card11");

        panel_contenLaporan.setBackground(new java.awt.Color(153, 255, 255));

        javax.swing.GroupLayout panel_contenLaporanLayout = new javax.swing.GroupLayout(panel_contenLaporan);
        panel_contenLaporan.setLayout(panel_contenLaporanLayout);
        panel_contenLaporanLayout.setHorizontalGroup(
            panel_contenLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1281, Short.MAX_VALUE)
        );
        panel_contenLaporanLayout.setVerticalGroup(
            panel_contenLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );

        ConntainerPanel.add(panel_contenLaporan, "card12");

        panel_contenDashbord.setBackground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout panel_contenDashbordLayout = new javax.swing.GroupLayout(panel_contenDashbord);
        panel_contenDashbord.setLayout(panel_contenDashbordLayout);
        panel_contenDashbordLayout.setHorizontalGroup(
            panel_contenDashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1281, Short.MAX_VALUE)
        );
        panel_contenDashbordLayout.setVerticalGroup(
            panel_contenDashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );

        ConntainerPanel.add(panel_contenDashbord, "card13");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel6.setText("Dashbord");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("BANAJ MOSLEM FRAGRANCE");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setText("Tegar");

        jLabel9.setText("Icon");

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel10.setText("20-Agustus-2020");

        javax.swing.GroupLayout header_panelLayout = new javax.swing.GroupLayout(header_panel);
        header_panel.setLayout(header_panelLayout);
        header_panelLayout.setHorizontalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_panelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_panelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel8))
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(10, 10, 10))
        );
        header_panelLayout.setVerticalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(10, 10, 10)
                .addComponent(jLabel7)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(navigasi_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(frame_logo_toko, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConntainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(header_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(ConntainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(frame_logo_toko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(navigasi_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void icon_dashbordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_dashbordMouseClicked
        // TODO add your handling code here:
        
        ConntainerPanel.removeAll();
        ConntainerPanel.add(panel_contenDashbord);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
        
        //visibilitas
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplayPink.png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));
        
    }//GEN-LAST:event_icon_dashbordMouseClicked

    private void icon_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_productMouseClicked
        // TODO add your handling code here:
        ConntainerPanel.removeAll();
        ConntainerPanel.add(panel_contenBarang);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
        
        //visibilitas icon
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfumePink.png")));
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));
        
        
    }//GEN-LAST:event_icon_productMouseClicked

    private void icon_managerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_managerMouseClicked
         // TODO add your handling code here:
          ConntainerPanel.removeAll();
        ConntainerPanel.add(panel_contenManageUser);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
        //visibilitas icon
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/manager (1).png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
        
        
    }//GEN-LAST:event_icon_managerMouseClicked

    private void icon_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_laporanMouseClicked
        // TODO add your handling code here:
        ConntainerPanel.removeAll();
        ConntainerPanel.add(panel_contenLaporan);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
        
        //visibilitas icon
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulsePink.png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
    }//GEN-LAST:event_icon_laporanMouseClicked

    private void icon_kasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_kasirMouseClicked
         // TODO add your handling code here:
        ConntainerPanel.removeAll();
        ConntainerPanel.add(panel_contenKasir);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
        
        //visibilitas icon
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cartPink.png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
        
        
        
    }//GEN-LAST:event_icon_kasirMouseClicked

    private void icon_settingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_settingMouseClicked

         // TODO add your handling code here:\
        ConntainerPanel.removeAll();

         // TODO add your handling code here:
        ConntainerPanel.removeAll();

        ConntainerPanel.add(panel_contenSetting);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
        
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingPink.png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));


         

    }//GEN-LAST:event_icon_settingMouseClicked

    private void panel_dashbord3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_dashbord3MouseClicked
        // TODO add your handling code here:
        
        ConntainerPanel.removeAll();
        ConntainerPanel.add(jLabel2);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
        
        
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/manager (1).png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
        
    }//GEN-LAST:event_panel_dashbord3MouseClicked

    private void panel_dashbordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_dashbordMouseClicked
        // TODO add your handling code here:
        
          ConntainerPanel.removeAll();
        ConntainerPanel.add(jLabel2);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
        
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplayPink.png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));
    }//GEN-LAST:event_panel_dashbordMouseClicked

    private void panel_dashbord2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_dashbord2MouseClicked
        // TODO add your handling code here:
        
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cartPink.png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
        
    }//GEN-LAST:event_panel_dashbord2MouseClicked

    private void panel_dashbord1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_dashbord1MouseClicked
        // TODO add your handling code here:
          ConntainerPanel.removeAll();
        ConntainerPanel.add(jLabel2);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
         //visibilitas icon
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfumePink.png")));
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));
    }//GEN-LAST:event_panel_dashbord1MouseClicked

    private void panel_dashbord4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_dashbord4MouseClicked
        // TODO add your handling code here:   
          ConntainerPanel.removeAll();
        ConntainerPanel.add(jLabel2);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
        
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulsePink.png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
    }//GEN-LAST:event_panel_dashbord4MouseClicked

    private void panel_dashbord5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_dashbord5MouseClicked
        // TODO add your handling code here:
        
        ConntainerPanel.removeAll();
        ConntainerPanel.add(jLabel2);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
        
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingPink.png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));
    }//GEN-LAST:event_panel_dashbord5MouseClicked

    private void icon_managerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_managerMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_icon_managerMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashbord().setVisible(true);
            }
        });
    }
    
    class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ConntainerPanel;
    private javax.swing.JPanel frame_logo_toko;
    private javax.swing.JPanel header_panel;
    private javax.swing.JLabel icon_dashbord;
    private javax.swing.JLabel icon_kasir;
    private javax.swing.JLabel icon_laporan;
    private javax.swing.JLabel icon_manager;
    private javax.swing.JLabel icon_product;
    private javax.swing.JLabel icon_setting;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel navigasi_panel;
    private javax.swing.JPanel panel_contenBarang;
    private javax.swing.JPanel panel_contenDashbord;
    private javax.swing.JPanel panel_contenKasir;
    private javax.swing.JPanel panel_contenLaporan;
    private javax.swing.JPanel panel_contenManageUser;
    private javax.swing.JPanel panel_contenSetting;
    private javax.swing.JPanel panel_dashbord;
    private javax.swing.JPanel panel_dashbord1;
    private javax.swing.JPanel panel_dashbord2;
    private javax.swing.JPanel panel_dashbord3;
    private javax.swing.JPanel panel_dashbord4;
    private javax.swing.JPanel panel_dashbord5;
    // End of variables declaration//GEN-END:variables
}
