/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.awt.Shape;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextField;
import service.barangService;

/**
 *
 * @author user
 */
public class Dashbord extends javax.swing.JFrame {

    /**
     * Creates new form Dashbord
     */
    
Dimension dimAx = Toolkit.getDefaultToolkit().getScreenSize();
Dimension dimIn = Toolkit.getDefaultToolkit().getBestCursorSize(1080, 720);
    public Dashbord() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setMaximumSize(dimAx);
        this.setMinimumSize(dimIn);
        this.setBackground(new Color(255,255,255));
       
        this.setLocationRelativeTo(null);
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplayPink.png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));
       
       
        
    }
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frame_logo_toko = new javax.swing.JPanel();
        navigasi_panel = new javax.swing.JPanel();
        panel_dashbord = new javax.swing.JPanel();
        icon_dashbord = new javax.swing.JLabel();
        panel_product = new javax.swing.JPanel();
        icon_product = new javax.swing.JLabel();
        panel_kasir = new javax.swing.JPanel();
        icon_kasir = new javax.swing.JLabel();
        panel_manager = new javax.swing.JPanel();
        icon_manager = new javax.swing.JLabel();
        panel_laporan = new javax.swing.JPanel();
        icon_laporan = new javax.swing.JLabel();
        panel_setting = new javax.swing.JPanel();
        icon_setting = new javax.swing.JLabel();
        ConntainerPanel = new javax.swing.JPanel();
        panel_contenDashbord = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panel_contenBarang = new javax.swing.JPanel();
        panel_navigasiBarang = new RoundedPanel(8, new Color(255, 255, 255));
        label_navigasi_barang = new javax.swing.JLabel();
        label_navigasi_Kategori = new javax.swing.JLabel();
        label_navigasi_supplier = new javax.swing.JLabel();
        label_navigasi_return = new javax.swing.JLabel();
        conten_manajemen = new javax.swing.JPanel();
        contenBarang = new javax.swing.JPanel();
        panel_totalBarang = new RoundedPanel(8, new Color(255, 255, 255));
        label_totalBarang = new javax.swing.JLabel();
        txt_totalBrg = new javax.swing.JLabel();
        comboBox_show = new javax.swing.JComboBox<>();
        panel_cariBarang = new RoundedPanel(8, new Color(255, 255, 255));
        txt_cariBrng = new javax.swing.JTextField();
        icon_cariBarang = new javax.swing.JLabel();
        panel_tablebarang = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_barang = new javax.swing.JTable();
        btn_TambahBarang = new javax.swing.JButton();
        contenKategori = new javax.swing.JPanel();
        panel_totalKategori = new RoundedPanel(8, new Color(255, 255, 255));
        label_totalBarang1 = new javax.swing.JLabel();
        txt_totalBrg1 = new javax.swing.JLabel();
        panel_cariKategori = new RoundedPanel(8, new Color(255, 255, 255));
        txt_cariKategori = new javax.swing.JTextField();
        icon_cariKategori = new javax.swing.JLabel();
        panel_tabelKategori = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabel_kategori = new javax.swing.JTable();
        btn_TambahBarang1 = new javax.swing.JButton();
        contenSupplier = new javax.swing.JPanel();
        panel_totalKategori1 = new RoundedPanel(8, new Color(255, 255, 255));
        label_totalBarang2 = new javax.swing.JLabel();
        txt_totalBrg2 = new javax.swing.JLabel();
        panel_cariKategori1 = new RoundedPanel(8, new Color(255, 255, 255));
        txt_cariKategori1 = new javax.swing.JTextField();
        icon_cariKategori1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        panel_contenKasir = new javax.swing.JPanel();
        panel_contenSetting = new javax.swing.JPanel();
        panel_contenManageUser = new javax.swing.JPanel();
        panel_contenLaporan = new javax.swing.JPanel();
        panel_navigasiLaporan = new RoundedPanel(8, Color.white);
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ContainerPanel_Laporan = new RoundedPanel(20, Color.white);
        ContainerPanel_LaporanTransaksi = new RoundedPanel(20, Color.white);
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_LaporanTransaksi = new javax.swing.JTable();
        ContainerPanel_LaporanPenjualan = new RoundedPanel(20, Color.white);
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_LaporanPenjualan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        header_panel = new RoundedPanel(8, new Color(250, 164, 164));
        label_page = new javax.swing.JLabel();
        label_namatoko = new javax.swing.JLabel();
        label_namauser = new javax.swing.JLabel();
        icon_user = new javax.swing.JLabel();
        label_tanggal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 51));

        frame_logo_toko.setBackground(new java.awt.Color(255, 255, 255));
        frame_logo_toko.setPreferredSize(new java.awt.Dimension(66, 66));

        javax.swing.GroupLayout frame_logo_tokoLayout = new javax.swing.GroupLayout(frame_logo_toko);
        frame_logo_toko.setLayout(frame_logo_tokoLayout);
        frame_logo_tokoLayout.setHorizontalGroup(
            frame_logo_tokoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        frame_logo_tokoLayout.setVerticalGroup(
            frame_logo_tokoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        navigasi_panel.setBackground(new java.awt.Color(255, 255, 255));

        panel_dashbord.setBackground(new java.awt.Color(255, 255, 255));
        panel_dashbord.setPreferredSize(new java.awt.Dimension(66, 60));
        panel_dashbord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_dashbordMouseClicked(evt);
            }
        });

        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png"))); // NOI18N
        icon_dashbord.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon_dashbord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_dashbordMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_dashbordLayout = new javax.swing.GroupLayout(panel_dashbord);
        panel_dashbord.setLayout(panel_dashbordLayout);
        panel_dashbordLayout.setHorizontalGroup(
            panel_dashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dashbordLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(icon_dashbord)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panel_dashbordLayout.setVerticalGroup(
            panel_dashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_dashbordLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(icon_dashbord)
                .addGap(19, 19, 19))
        );

        panel_product.setBackground(new java.awt.Color(255, 255, 255));
        panel_product.setPreferredSize(new java.awt.Dimension(66, 60));
        panel_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_productMouseClicked(evt);
            }
        });

        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png"))); // NOI18N
        icon_product.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_productMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_productLayout = new javax.swing.GroupLayout(panel_product);
        panel_product.setLayout(panel_productLayout);
        panel_productLayout.setHorizontalGroup(
            panel_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_productLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(icon_product)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_productLayout.setVerticalGroup(
            panel_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_productLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(icon_product)
                .addGap(19, 19, 19))
        );

        panel_kasir.setBackground(new java.awt.Color(255, 255, 255));
        panel_kasir.setPreferredSize(new java.awt.Dimension(66, 60));
        panel_kasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_kasirMouseClicked(evt);
            }
        });

        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png"))); // NOI18N
        icon_kasir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon_kasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_kasirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_kasirLayout = new javax.swing.GroupLayout(panel_kasir);
        panel_kasir.setLayout(panel_kasirLayout);
        panel_kasirLayout.setHorizontalGroup(
            panel_kasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_kasirLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(icon_kasir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_kasirLayout.setVerticalGroup(
            panel_kasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_kasirLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(icon_kasir)
                .addGap(19, 19, 19))
        );

        panel_manager.setBackground(new java.awt.Color(255, 255, 255));
        panel_manager.setPreferredSize(new java.awt.Dimension(66, 60));
        panel_manager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_managerMouseClicked(evt);
            }
        });

        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png"))); // NOI18N
        icon_manager.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon_manager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_managerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icon_managerMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panel_managerLayout = new javax.swing.GroupLayout(panel_manager);
        panel_manager.setLayout(panel_managerLayout);
        panel_managerLayout.setHorizontalGroup(
            panel_managerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_managerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(icon_manager)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panel_managerLayout.setVerticalGroup(
            panel_managerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_managerLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(icon_manager)
                .addGap(19, 19, 19))
        );

        panel_laporan.setBackground(new java.awt.Color(255, 255, 255));
        panel_laporan.setPreferredSize(new java.awt.Dimension(66, 60));
        panel_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_laporanMouseClicked(evt);
            }
        });

        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png"))); // NOI18N
        icon_laporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_laporanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_laporanLayout = new javax.swing.GroupLayout(panel_laporan);
        panel_laporan.setLayout(panel_laporanLayout);
        panel_laporanLayout.setHorizontalGroup(
            panel_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_laporanLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(icon_laporan)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panel_laporanLayout.setVerticalGroup(
            panel_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_laporanLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(icon_laporan)
                .addGap(19, 19, 19))
        );

        panel_setting.setBackground(new java.awt.Color(255, 255, 255));
        panel_setting.setPreferredSize(new java.awt.Dimension(66, 60));
        panel_setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_settingMouseClicked(evt);
            }
        });

        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png"))); // NOI18N
        icon_setting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon_setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_settingMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_settingLayout = new javax.swing.GroupLayout(panel_setting);
        panel_setting.setLayout(panel_settingLayout);
        panel_settingLayout.setHorizontalGroup(
            panel_settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_settingLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(icon_setting)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panel_settingLayout.setVerticalGroup(
            panel_settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_settingLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(icon_setting)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout navigasi_panelLayout = new javax.swing.GroupLayout(navigasi_panel);
        navigasi_panel.setLayout(navigasi_panelLayout);
        navigasi_panelLayout.setHorizontalGroup(
            navigasi_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_kasir, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
            .addComponent(panel_product, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
            .addComponent(panel_dashbord, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panel_manager, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panel_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panel_setting, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        navigasi_panelLayout.setVerticalGroup(
            navigasi_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigasi_panelLayout.createSequentialGroup()
                .addComponent(panel_dashbord, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_kasir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_product, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_manager, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_setting, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        ConntainerPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_contenDashbordLayout = new javax.swing.GroupLayout(panel_contenDashbord);
        panel_contenDashbord.setLayout(panel_contenDashbordLayout);
        panel_contenDashbordLayout.setHorizontalGroup(
            panel_contenDashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_contenDashbordLayout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(835, Short.MAX_VALUE))
        );
        panel_contenDashbordLayout.setVerticalGroup(
            panel_contenDashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_contenDashbordLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(327, Short.MAX_VALUE))
        );

        ConntainerPanel.add(panel_contenDashbord, "card13");

        panel_contenBarang.setForeground(new java.awt.Color(255, 255, 255));

        label_navigasi_barang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_navigasi_barang.setText("Barang");
        label_navigasi_barang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_navigasi_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_navigasi_barangMouseClicked(evt);
            }
        });

        label_navigasi_Kategori.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_navigasi_Kategori.setText("Kategori");
        label_navigasi_Kategori.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_navigasi_Kategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_navigasi_KategoriMouseClicked(evt);
            }
        });

        label_navigasi_supplier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_navigasi_supplier.setText("Supplier");
        label_navigasi_supplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_navigasi_supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_navigasi_supplierMouseClicked(evt);
            }
        });

        label_navigasi_return.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_navigasi_return.setText("Return");
        label_navigasi_return.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_navigasi_return.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_navigasi_returnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_navigasiBarangLayout = new javax.swing.GroupLayout(panel_navigasiBarang);
        panel_navigasiBarang.setLayout(panel_navigasiBarangLayout);
        panel_navigasiBarangLayout.setHorizontalGroup(
            panel_navigasiBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_navigasiBarangLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(label_navigasi_barang)
                .addGap(29, 29, 29)
                .addComponent(label_navigasi_Kategori)
                .addGap(18, 18, 18)
                .addComponent(label_navigasi_supplier)
                .addGap(18, 18, 18)
                .addComponent(label_navigasi_return)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        panel_navigasiBarangLayout.setVerticalGroup(
            panel_navigasiBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_navigasiBarangLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(panel_navigasiBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_navigasi_barang)
                    .addComponent(label_navigasi_Kategori)
                    .addComponent(label_navigasi_supplier)
                    .addComponent(label_navigasi_return))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        conten_manajemen.setPreferredSize(new java.awt.Dimension(1200, 358));
        conten_manajemen.setLayout(new java.awt.CardLayout());

        label_totalBarang.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        label_totalBarang.setText("Total Barang");

        txt_totalBrg.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        txt_totalBrg.setText("1020");

        javax.swing.GroupLayout panel_totalBarangLayout = new javax.swing.GroupLayout(panel_totalBarang);
        panel_totalBarang.setLayout(panel_totalBarangLayout);
        panel_totalBarangLayout.setHorizontalGroup(
            panel_totalBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_totalBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_totalBarang)
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_totalBarangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_totalBrg)
                .addGap(18, 18, 18))
        );
        panel_totalBarangLayout.setVerticalGroup(
            panel_totalBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_totalBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_totalBarang)
                .addGap(26, 26, 26)
                .addComponent(txt_totalBrg)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        comboBox_show.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kategori" }));
        comboBox_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_showActionPerformed(evt);
            }
        });

        icon_cariBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/magnifying-glass.png"))); // NOI18N

        javax.swing.GroupLayout panel_cariBarangLayout = new javax.swing.GroupLayout(panel_cariBarang);
        panel_cariBarang.setLayout(panel_cariBarangLayout);
        panel_cariBarangLayout.setHorizontalGroup(
            panel_cariBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cariBarangLayout.createSequentialGroup()
                .addComponent(txt_cariBrng, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icon_cariBarang)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        panel_cariBarangLayout.setVerticalGroup(
            panel_cariBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cariBarangLayout.createSequentialGroup()
                .addGroup(panel_cariBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_cariBrng, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon_cariBarang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        txt_cariBrng.setBorder(javax.swing.BorderFactory.createEmptyBorder());

        table_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(table_barang);

        javax.swing.GroupLayout panel_tablebarangLayout = new javax.swing.GroupLayout(panel_tablebarang);
        panel_tablebarang.setLayout(panel_tablebarangLayout);
        panel_tablebarangLayout.setHorizontalGroup(
            panel_tablebarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        panel_tablebarangLayout.setVerticalGroup(
            panel_tablebarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tablebarangLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btn_TambahBarang.setBackground(new java.awt.Color(250, 164, 164));
        btn_TambahBarang.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btn_TambahBarang.setText("Tambah");
        btn_TambahBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_TambahBarangMouseClicked(evt);
            }
        });
        btn_TambahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TambahBarangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contenBarangLayout = new javax.swing.GroupLayout(contenBarang);
        contenBarang.setLayout(contenBarangLayout);
        contenBarangLayout.setHorizontalGroup(
            contenBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenBarangLayout.createSequentialGroup()
                .addComponent(panel_totalBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panel_tablebarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(contenBarangLayout.createSequentialGroup()
                .addComponent(panel_cariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBox_show, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 658, Short.MAX_VALUE)
                .addComponent(btn_TambahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        contenBarangLayout.setVerticalGroup(
            contenBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenBarangLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panel_totalBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(contenBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_cariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contenBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_TambahBarang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(comboBox_show, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(13, 13, 13)
                .addComponent(panel_tablebarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        conten_manajemen.add(contenBarang, "card9");

        label_totalBarang1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        label_totalBarang1.setText("Total Kategori");

        txt_totalBrg1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        txt_totalBrg1.setText("1020");

        javax.swing.GroupLayout panel_totalKategoriLayout = new javax.swing.GroupLayout(panel_totalKategori);
        panel_totalKategori.setLayout(panel_totalKategoriLayout);
        panel_totalKategoriLayout.setHorizontalGroup(
            panel_totalKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_totalKategoriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_totalBarang1)
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_totalKategoriLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_totalBrg1)
                .addGap(18, 18, 18))
        );
        panel_totalKategoriLayout.setVerticalGroup(
            panel_totalKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_totalKategoriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_totalBarang1)
                .addGap(26, 26, 26)
                .addComponent(txt_totalBrg1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        icon_cariKategori.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/magnifying-glass.png"))); // NOI18N

        javax.swing.GroupLayout panel_cariKategoriLayout = new javax.swing.GroupLayout(panel_cariKategori);
        panel_cariKategori.setLayout(panel_cariKategoriLayout);
        panel_cariKategoriLayout.setHorizontalGroup(
            panel_cariKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cariKategoriLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(txt_cariKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icon_cariKategori)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        panel_cariKategoriLayout.setVerticalGroup(
            panel_cariKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_cariKategori)
            .addGroup(panel_cariKategoriLayout.createSequentialGroup()
                .addComponent(icon_cariKategori)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        txt_cariKategori.setBorder(javax.swing.BorderFactory.createEmptyBorder());

        tabel_kategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabel_kategori);

        javax.swing.GroupLayout panel_tabelKategoriLayout = new javax.swing.GroupLayout(panel_tabelKategori);
        panel_tabelKategori.setLayout(panel_tabelKategoriLayout);
        panel_tabelKategoriLayout.setHorizontalGroup(
            panel_tabelKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1221, Short.MAX_VALUE)
        );
        panel_tabelKategoriLayout.setVerticalGroup(
            panel_tabelKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tabelKategoriLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        btn_TambahBarang1.setBackground(new java.awt.Color(250, 164, 164));
        btn_TambahBarang1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btn_TambahBarang1.setText("Tambah");
        btn_TambahBarang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_TambahBarang1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout contenKategoriLayout = new javax.swing.GroupLayout(contenKategori);
        contenKategori.setLayout(contenKategoriLayout);
        contenKategoriLayout.setHorizontalGroup(
            contenKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_tabelKategori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(contenKategoriLayout.createSequentialGroup()
                .addComponent(panel_cariKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_TambahBarang1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(contenKategoriLayout.createSequentialGroup()
                .addComponent(panel_totalKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        contenKategoriLayout.setVerticalGroup(
            contenKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenKategoriLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panel_totalKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(contenKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_TambahBarang1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_cariKategori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addComponent(panel_tabelKategori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        conten_manajemen.add(contenKategori, "card3");

        label_totalBarang2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        label_totalBarang2.setText("Total Supplier");

        txt_totalBrg2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        txt_totalBrg2.setText("1020");

        javax.swing.GroupLayout panel_totalKategori1Layout = new javax.swing.GroupLayout(panel_totalKategori1);
        panel_totalKategori1.setLayout(panel_totalKategori1Layout);
        panel_totalKategori1Layout.setHorizontalGroup(
            panel_totalKategori1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_totalKategori1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_totalBarang2)
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_totalKategori1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_totalBrg2)
                .addGap(18, 18, 18))
        );
        panel_totalKategori1Layout.setVerticalGroup(
            panel_totalKategori1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_totalKategori1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_totalBarang2)
                .addGap(26, 26, 26)
                .addComponent(txt_totalBrg2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        txt_cariKategori1.setBorder(null);

        icon_cariKategori1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/magnifying-glass.png"))); // NOI18N

        javax.swing.GroupLayout panel_cariKategori1Layout = new javax.swing.GroupLayout(panel_cariKategori1);
        panel_cariKategori1.setLayout(panel_cariKategori1Layout);
        panel_cariKategori1Layout.setHorizontalGroup(
            panel_cariKategori1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cariKategori1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(txt_cariKategori1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icon_cariKategori1)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        panel_cariKategori1Layout.setVerticalGroup(
            panel_cariKategori1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cariKategori1Layout.createSequentialGroup()
                .addGroup(panel_cariKategori1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_cariKategori1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon_cariKategori1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        txt_cariKategori1.setBorder(javax.swing.BorderFactory.createEmptyBorder());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1221, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
        );

        jButton1.setBackground(new java.awt.Color(250, 164, 164));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton1.setText("Tambah");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contenSupplierLayout = new javax.swing.GroupLayout(contenSupplier);
        contenSupplier.setLayout(contenSupplierLayout);
        contenSupplierLayout.setHorizontalGroup(
            contenSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(contenSupplierLayout.createSequentialGroup()
                .addComponent(panel_totalKategori1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(contenSupplierLayout.createSequentialGroup()
                .addComponent(panel_cariKategori1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        contenSupplierLayout.setVerticalGroup(
            contenSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenSupplierLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panel_totalKategori1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(contenSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_cariKategori1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        conten_manajemen.add(contenSupplier, "card4");

        javax.swing.GroupLayout panel_contenBarangLayout = new javax.swing.GroupLayout(panel_contenBarang);
        panel_contenBarang.setLayout(panel_contenBarangLayout);
        panel_contenBarangLayout.setHorizontalGroup(
            panel_contenBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_contenBarangLayout.createSequentialGroup()
                .addGroup(panel_contenBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_contenBarangLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panel_navigasiBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_contenBarangLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(conten_manajemen, javax.swing.GroupLayout.PREFERRED_SIZE, 1221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panel_contenBarangLayout.setVerticalGroup(
            panel_contenBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_contenBarangLayout.createSequentialGroup()
                .addComponent(panel_navigasiBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(conten_manajemen, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(311, 311, 311))
        );

        ConntainerPanel.add(panel_contenBarang, "card8");

        javax.swing.GroupLayout panel_contenKasirLayout = new javax.swing.GroupLayout(panel_contenKasir);
        panel_contenKasir.setLayout(panel_contenKasirLayout);
        panel_contenKasirLayout.setHorizontalGroup(
            panel_contenKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1259, Short.MAX_VALUE)
        );
        panel_contenKasirLayout.setVerticalGroup(
            panel_contenKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        ConntainerPanel.add(panel_contenKasir, "card9");

        javax.swing.GroupLayout panel_contenSettingLayout = new javax.swing.GroupLayout(panel_contenSetting);
        panel_contenSetting.setLayout(panel_contenSettingLayout);
        panel_contenSettingLayout.setHorizontalGroup(
            panel_contenSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1259, Short.MAX_VALUE)
        );
        panel_contenSettingLayout.setVerticalGroup(
            panel_contenSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        ConntainerPanel.add(panel_contenSetting, "card10");

        javax.swing.GroupLayout panel_contenManageUserLayout = new javax.swing.GroupLayout(panel_contenManageUser);
        panel_contenManageUser.setLayout(panel_contenManageUserLayout);
        panel_contenManageUserLayout.setHorizontalGroup(
            panel_contenManageUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1259, Short.MAX_VALUE)
        );
        panel_contenManageUserLayout.setVerticalGroup(
            panel_contenManageUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        ConntainerPanel.add(panel_contenManageUser, "card11");

        panel_contenLaporan.setPreferredSize(new java.awt.Dimension(1281, 663));

        panel_navigasiLaporan.setPreferredSize(new java.awt.Dimension(470, 100));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setText("Laporan Penjualan");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setText("Laporan Pembelian");

        javax.swing.GroupLayout panel_navigasiLaporanLayout = new javax.swing.GroupLayout(panel_navigasiLaporan);
        panel_navigasiLaporan.setLayout(panel_navigasiLaporanLayout);
        panel_navigasiLaporanLayout.setHorizontalGroup(
            panel_navigasiLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_navigasiLaporanLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(10, 10, 10))
        );
        panel_navigasiLaporanLayout.setVerticalGroup(
            panel_navigasiLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_navigasiLaporanLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panel_navigasiLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(5, 5, 5))
        );

        ContainerPanel_Laporan.setLayout(new java.awt.CardLayout());

        Table_LaporanTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No.", "Id Transaksi", "Supplier", "Tanggal Transaksi", "Total Barang", "Total Return", "Total Harga"
            }
        ));
        jScrollPane1.setViewportView(Table_LaporanTransaksi);

        javax.swing.GroupLayout ContainerPanel_LaporanTransaksiLayout = new javax.swing.GroupLayout(ContainerPanel_LaporanTransaksi);
        ContainerPanel_LaporanTransaksi.setLayout(ContainerPanel_LaporanTransaksiLayout);
        ContainerPanel_LaporanTransaksiLayout.setHorizontalGroup(
            ContainerPanel_LaporanTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1242, Short.MAX_VALUE)
        );
        ContainerPanel_LaporanTransaksiLayout.setVerticalGroup(
            ContainerPanel_LaporanTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContainerPanel_LaporanTransaksiLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );

        ContainerPanel_Laporan.add(ContainerPanel_LaporanTransaksi, "card2");

        Table_LaporanPenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No.", "Id Transaksi", "Kasir", "Tanggal Transaksi", "Total Barang", "Total Return", "Total Harga"
            }
        ));
        jScrollPane2.setViewportView(Table_LaporanPenjualan);

        javax.swing.GroupLayout ContainerPanel_LaporanPenjualanLayout = new javax.swing.GroupLayout(ContainerPanel_LaporanPenjualan);
        ContainerPanel_LaporanPenjualan.setLayout(ContainerPanel_LaporanPenjualanLayout);
        ContainerPanel_LaporanPenjualanLayout.setHorizontalGroup(
            ContainerPanel_LaporanPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerPanel_LaporanPenjualanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1222, Short.MAX_VALUE)
                .addContainerGap())
        );
        ContainerPanel_LaporanPenjualanLayout.setVerticalGroup(
            ContainerPanel_LaporanPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerPanel_LaporanPenjualanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addContainerGap())
        );

        ContainerPanel_Laporan.add(ContainerPanel_LaporanPenjualan, "card2");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setText("Show ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Minggu", "1 Bulan" }));

        jButton2.setBackground(new java.awt.Color(250, 164, 164));
        jButton2.setText("Export");

        javax.swing.GroupLayout panel_contenLaporanLayout = new javax.swing.GroupLayout(panel_contenLaporan);
        panel_contenLaporan.setLayout(panel_contenLaporanLayout);
        panel_contenLaporanLayout.setHorizontalGroup(
            panel_contenLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_contenLaporanLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel_contenLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContainerPanel_Laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 1242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_navigasiLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_contenLaporanLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        panel_contenLaporanLayout.setVerticalGroup(
            panel_contenLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_contenLaporanLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panel_navigasiLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(panel_contenLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(ContainerPanel_Laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ConntainerPanel.add(panel_contenLaporan, "card12");

        header_panel.setPreferredSize(new java.awt.Dimension(1500, 86));

        label_page.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        label_page.setForeground(new java.awt.Color(255, 255, 255));
        label_page.setText("Dashbord");

        label_namatoko.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label_namatoko.setForeground(new java.awt.Color(255, 255, 255));
        label_namatoko.setText("BANAJ MOSLEM FRAGRANCE");

        label_namauser.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        label_namauser.setForeground(new java.awt.Color(255, 255, 255));
        label_namauser.setText("Tegar");

        icon_user.setText("Icon");

        label_tanggal.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        label_tanggal.setForeground(new java.awt.Color(255, 255, 255));
        label_tanggal.setText("20-Agustus-2020");

        javax.swing.GroupLayout header_panelLayout = new javax.swing.GroupLayout(header_panel);
        header_panel.setLayout(header_panelLayout);
        header_panelLayout.setHorizontalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_panelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_page)
                    .addComponent(label_namatoko))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 726, Short.MAX_VALUE)
                .addGroup(header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_panelLayout.createSequentialGroup()
                        .addComponent(icon_user)
                        .addGap(49, 49, 49)
                        .addComponent(label_namauser))
                    .addComponent(label_tanggal, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(10, 10, 10))
        );
        header_panelLayout.setVerticalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_page)
                .addGap(10, 10, 10)
                .addComponent(label_namatoko)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_namauser)
                    .addComponent(icon_user))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_tanggal)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(navigasi_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(frame_logo_toko, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConntainerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(header_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(header_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConntainerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(frame_logo_toko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(navigasi_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void icon_dashbordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_dashbordMouseClicked
        // TODO add your handling code here:
        
        ConntainerPanel.removeAll();
        ConntainerPanel.add(panel_contenDashbord);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
        
        //visibilitas
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplayPink.png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));
        
        //set Label Page
        label_page.setText("Dashbord");
        
    }//GEN-LAST:event_icon_dashbordMouseClicked

    private void icon_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_productMouseClicked
         // TODO add your handling code here:
        ConntainerPanel.removeAll();
        ConntainerPanel.add(panel_contenBarang);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
        conten_manajemen.removeAll();
        conten_manajemen.add(contenBarang);
        conten_manajemen.repaint();
        conten_manajemen.revalidate();
        
        
        //visibilitas icon
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfumePink.png")));
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));
        //visibilitas label navigasi
        label_navigasi_barang.setForeground(new Color(255, 164, 164));
        label_navigasi_Kategori.setForeground(new Color(0, 0, 0));
        label_navigasi_supplier.setForeground(new Color(0, 0, 0));
        label_navigasi_return.setForeground(new Color(0, 0, 0));
        
        //set Text labelPage
        label_page.setText("Manajemen Product");
        
        barangService br = new barangService();
        br.showBarang(table_barang);
        
    }//GEN-LAST:event_icon_productMouseClicked

    private void icon_managerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_managerMouseClicked
         // TODO add your handling code here:
          ConntainerPanel.removeAll();
        ConntainerPanel.add(panel_contenManageUser);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
        //visibilitas icon
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/manager (1).png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
        
          
        //set Text labelPage
        label_page.setText("User Management");
        
        
    }//GEN-LAST:event_icon_managerMouseClicked

    private void icon_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_laporanMouseClicked
        // TODO add your handling code here:
        ConntainerPanel.removeAll();
        ConntainerPanel.add(panel_contenLaporan);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
        
        //visibilitas icon
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulsePink.png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
        
          
        //set Text labelPage
        label_page.setText("Laporan Transaksi");
    }//GEN-LAST:event_icon_laporanMouseClicked

    private void icon_kasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_kasirMouseClicked
         // TODO add your handling code here:
        ConntainerPanel.removeAll();
        ConntainerPanel.add(panel_contenKasir);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
        
        //visibilitas icon
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cartPink.png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
        
        //set label Page
        label_page.setText("Kasir");
        
    }//GEN-LAST:event_icon_kasirMouseClicked

    private void icon_settingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_settingMouseClicked

         // TODO add your handling code here:\
        
        ConntainerPanel.removeAll();
        ConntainerPanel.add(panel_contenSetting);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
        
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingPink.png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));


           
        //set Text labelPage
        label_page.setText("Setting's");

    }//GEN-LAST:event_icon_settingMouseClicked

    private void panel_managerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_managerMouseClicked
        // TODO add your handling code here:
        
        ConntainerPanel.removeAll();
        ConntainerPanel.add(panel_contenManageUser);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
        
        
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/manager (1).png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
        
    }//GEN-LAST:event_panel_managerMouseClicked

    private void panel_dashbordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_dashbordMouseClicked
        // TODO add your handling code here:
        
        ConntainerPanel.removeAll();
        ConntainerPanel.add(panel_contenDashbord);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
        
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplayPink.png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));
    }//GEN-LAST:event_panel_dashbordMouseClicked

    private void panel_kasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_kasirMouseClicked
        // TODO add your handling code here:
        ConntainerPanel.removeAll();
        ConntainerPanel.add(panel_contenKasir);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
        
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cartPink.png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
        
    }//GEN-LAST:event_panel_kasirMouseClicked

    private void panel_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_productMouseClicked
        // TODO add your handling code here:
        ConntainerPanel.removeAll();
        ConntainerPanel.add(panel_contenBarang);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
         //visibilitas icon
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfumePink.png")));
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));
    }//GEN-LAST:event_panel_productMouseClicked

    private void panel_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_laporanMouseClicked
        // TODO add your handling code here:   
          ConntainerPanel.removeAll();
        ConntainerPanel.add(panel_contenLaporan);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
        
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulsePink.png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingWhite.png")));
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
        
        
        
    }//GEN-LAST:event_panel_laporanMouseClicked

    private void panel_settingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_settingMouseClicked
        // TODO add your handling code here:
        
        ConntainerPanel.removeAll();
        ConntainerPanel.add(panel_contenSetting);
        ConntainerPanel.repaint();
        ConntainerPanel.revalidate();
        
        icon_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/parfume.png")));
        icon_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cart (1).png")));
        icon_dashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/airplay (1).png")));
        icon_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settingPink.png")));
        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pulse (1).png")));
        icon_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/managerWhite.png")));
    }//GEN-LAST:event_panel_settingMouseClicked

    private void icon_managerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_managerMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_icon_managerMouseEntered

    private void label_navigasi_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_navigasi_barangMouseClicked
          // TODO add your handling code here:
          
          label_navigasi_barang.setForeground(new Color(255, 164, 164));
          label_navigasi_Kategori.setForeground(new Color(0, 0, 0));
          label_navigasi_supplier.setForeground(new Color(0, 0, 0));
          label_navigasi_return.setForeground(new Color(0, 0, 0));
          
          conten_manajemen.removeAll();
          conten_manajemen.add(contenBarang);
          conten_manajemen.repaint();
          conten_manajemen.revalidate();
         
         
    }//GEN-LAST:event_label_navigasi_barangMouseClicked

    private void label_navigasi_KategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_navigasi_KategoriMouseClicked
         // TODO add your handling code here:
         //visibiliras label navigasi
          label_navigasi_barang.setForeground(new Color(0, 0, 0));
          label_navigasi_Kategori.setForeground(new Color(255, 164, 164));
          label_navigasi_supplier.setForeground(new Color(0, 0, 0));
          label_navigasi_return.setForeground(new Color(0, 0, 0));
          
          conten_manajemen.removeAll();
          conten_manajemen.add(contenKategori);
          conten_manajemen.repaint();
          conten_manajemen.revalidate();
    }//GEN-LAST:event_label_navigasi_KategoriMouseClicked

    private void label_navigasi_supplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_navigasi_supplierMouseClicked
         // TODO add your handling code here:
         
          label_navigasi_barang.setForeground(new Color(0, 0, 0));
          label_navigasi_Kategori.setForeground(new Color(0, 0, 0));
          label_navigasi_supplier.setForeground(new Color(255, 164, 164));
          label_navigasi_return.setForeground(new Color(0, 0, 0));
          
          conten_manajemen.removeAll();
          conten_manajemen.add(contenSupplier);
          conten_manajemen.repaint();
          conten_manajemen.revalidate();
    }//GEN-LAST:event_label_navigasi_supplierMouseClicked

    private void label_navigasi_returnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_navigasi_returnMouseClicked
         // TODO add your handling code here:
         
          label_navigasi_barang.setForeground(new Color(0, 0, 0));
          label_navigasi_Kategori.setForeground(new Color(0, 0, 0));
          label_navigasi_supplier.setForeground(new Color(0, 0, 0));
          label_navigasi_return.setForeground(new Color(255, 164, 164));
    }//GEN-LAST:event_label_navigasi_returnMouseClicked

    private void comboBox_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_showActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBox_showActionPerformed

    private void btn_TambahBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TambahBarangMouseClicked
        // TODO add your handling code here:
        JFrame jfDataTambahBarang = new DataBarangTambah();
        jfDataTambahBarang.show();
    }//GEN-LAST:event_btn_TambahBarangMouseClicked

    private void btn_TambahBarang1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TambahBarang1MouseClicked
        // TODO add your handling code here:
        
        JFrame jfTambahKategori = new DataTambahKategori();
        jfTambahKategori.show();
    }//GEN-LAST:event_btn_TambahBarang1MouseClicked

    private void btn_TambahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TambahBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_TambahBarangActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
          // TODO add your handling code here:
          JFrame jfSupplier = new DataTambahSupplier();
          jfSupplier.show();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashbord().setVisible(true);
            }
        });
    }
    
    class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
        
        
    }
    public class RoundJTextField extends JTextField {
    private Shape shape;
    public RoundJTextField(int size) {
        super(size);
        setOpaque(false); // As suggested by @AVD in comment.
    }
    protected void paintComponent(Graphics g) {
         g.setColor(getBackground());
         g.fillRoundRect(0, 0, getWidth()-1, getHeight()-1, 15, 15);
         super.paintComponent(g);
    }
    protected void paintBorder(Graphics g) {
         g.setColor(getForeground());
         g.drawRoundRect(0, 0, getWidth()-1, getHeight()-1, 15, 15);
    }
    public boolean contains(int x, int y) {
         if (shape == null || !shape.getBounds().equals(getBounds())) {
             shape = new RoundRectangle2D.Float(0, 0, getWidth()-1, getHeight()-1, 15, 15);
         }
         return shape.contains(x, y);
    }
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ConntainerPanel;
    private javax.swing.JPanel ContainerPanel_Laporan;
    private javax.swing.JPanel ContainerPanel_LaporanPenjualan;
    private javax.swing.JPanel ContainerPanel_LaporanTransaksi;
    private javax.swing.JTable Table_LaporanPenjualan;
    private javax.swing.JTable Table_LaporanTransaksi;
    private javax.swing.JButton btn_TambahBarang;
    private javax.swing.JButton btn_TambahBarang1;
    private javax.swing.JComboBox<String> comboBox_show;
    private javax.swing.JPanel contenBarang;
    private javax.swing.JPanel contenKategori;
    private javax.swing.JPanel contenSupplier;
    private javax.swing.JPanel conten_manajemen;
    private javax.swing.JPanel frame_logo_toko;
    private javax.swing.JPanel header_panel;
    private javax.swing.JLabel icon_cariBarang;
    private javax.swing.JLabel icon_cariKategori;
    private javax.swing.JLabel icon_cariKategori1;
    private javax.swing.JLabel icon_dashbord;
    private javax.swing.JLabel icon_kasir;
    private javax.swing.JLabel icon_laporan;
    private javax.swing.JLabel icon_manager;
    private javax.swing.JLabel icon_product;
    private javax.swing.JLabel icon_setting;
    private javax.swing.JLabel icon_user;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label_namatoko;
    private javax.swing.JLabel label_namauser;
    private javax.swing.JLabel label_navigasi_Kategori;
    private javax.swing.JLabel label_navigasi_barang;
    private javax.swing.JLabel label_navigasi_return;
    private javax.swing.JLabel label_navigasi_supplier;
    private javax.swing.JLabel label_page;
    private javax.swing.JLabel label_tanggal;
    private javax.swing.JLabel label_totalBarang;
    private javax.swing.JLabel label_totalBarang1;
    private javax.swing.JLabel label_totalBarang2;
    private javax.swing.JPanel navigasi_panel;
    private javax.swing.JPanel panel_cariBarang;
    private javax.swing.JPanel panel_cariKategori;
    private javax.swing.JPanel panel_cariKategori1;
    private javax.swing.JPanel panel_contenBarang;
    private javax.swing.JPanel panel_contenDashbord;
    private javax.swing.JPanel panel_contenKasir;
    private javax.swing.JPanel panel_contenLaporan;
    private javax.swing.JPanel panel_contenManageUser;
    private javax.swing.JPanel panel_contenSetting;
    private javax.swing.JPanel panel_dashbord;
    private javax.swing.JPanel panel_kasir;
    private javax.swing.JPanel panel_laporan;
    private javax.swing.JPanel panel_manager;
    private javax.swing.JPanel panel_navigasiBarang;
    private javax.swing.JPanel panel_navigasiLaporan;
    private javax.swing.JPanel panel_product;
    private javax.swing.JPanel panel_setting;
    private javax.swing.JPanel panel_tabelKategori;
    private javax.swing.JPanel panel_tablebarang;
    private javax.swing.JPanel panel_totalBarang;
    private javax.swing.JPanel panel_totalKategori;
    private javax.swing.JPanel panel_totalKategori1;
    private javax.swing.JTable tabel_kategori;
    private javax.swing.JTable table_barang;
    private javax.swing.JTextField txt_cariBrng;
    private javax.swing.JTextField txt_cariKategori;
    private javax.swing.JTextField txt_cariKategori1;
    private javax.swing.JLabel txt_totalBrg;
    private javax.swing.JLabel txt_totalBrg1;
    private javax.swing.JLabel txt_totalBrg2;
    // End of variables declaration//GEN-END:variables
}
