/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Repository.Barang;
import Repository.BarangInterface;
import Repository.Database;
import Repository.DatabaseInterface;
import Repository.Kategori;
import Repository.KategoriInterface;
import Repository.Supplier;
import Repository.SupplierInterface;
import Util.tanggalSaatIni;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
 import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import service.barangService;
import service.supplierService;
 

/**
 *
 * @author user
 */
public class DataBarangTambah extends javax.swing.JFrame {

    /**
     * Creates new form DataBarangTambah
     */
    ImageIcon suscesicon =  new ImageIcon(getClass().getResource("/picture/checked.png"));
    ImageIcon eroricon =  new ImageIcon(getClass().getResource("/picture/warning.png"));
    public DataBarangTambah() {
        initComponents();
        this.setSize(1080,600);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Tambah Barang");
        
        //set value combo kategori
        barangService br = new barangService();
        br.addItemInCombobox(combo_kategori);
        supplierService su = new supplierService();
        su.addItemSupplier(combo_supplier);
        txt_addAt.setEnabled(false);
        String kode="";
        txt_barangRusak.setText("0");
        kode_barang_Edit.setEnabled(false);
        br.addItemInCombobox(kategori_edit);
        su.addItemSupplier(supplier_edit);
        kode_barangLama.setVisible(true);
        namaBarangLama.setVisible(false);
        kategori_lama.setVisible(true);
        supplierLama.setVisible(false);
        harga_beliLama.setVisible(false);
        harga_jualLama.setVisible(false);
        stok_lama.setVisible(false);
        rusak_lama.setVisible(false);
        update_atEdit.setEnabled(false);
        total_stok.setEnabled(false);
        label_stokEdit.setVisible(false);
        this.txt_stokEdit.setEnabled(false);
        this.barang_RusakEdit.setEnabled(false);
        this.txt_barangRusak.setVisible(false);
        this.barang_RusakEdit.setVisible(false);
        this.total_stok.setVisible(false);
        this.kategori_lama.setVisible(false);
        this.kode_barangLama.setVisible(false);
        
        
        

    }

    public String getNama_barangEdit() {
        return nama_barangEdit.toString();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navigasiPanel = new RoundedPanel(8, new Color(255, 255, 255));
        label_navigasi = new javax.swing.JLabel();
        id_transaksi = new javax.swing.JLabel();
        labelTransaksi = new javax.swing.JLabel();
        txt_barangRusak = new javax.swing.JTextField();
        barang_RusakEdit = new javax.swing.JTextField();
        total_stok = new javax.swing.JTextField();
        MainConten = new RoundedPanel(8, new Color(255, 255, 255));
        contenAddBarang = new RoundedPanel(8, new Color(255, 255, 255));
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_kodeBarang = new javax.swing.JTextField();
        txt_nama_barang = new javax.swing.JTextField();
        combo_supplier = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txt_stok = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_addAt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        combo_kategori = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txt_hargaBeli = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_hargaJual = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btn_simpanAdd = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        kode_brg_lama = new javax.swing.JLabel();
        contenEditBarang = new RoundedPanel(8, new Color(255, 255, 255));
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        kode_barang_Edit = new javax.swing.JTextField();
        nama_barangEdit = new javax.swing.JTextField();
        supplier_edit = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        update_atEdit = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        kategori_edit = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        harga_beliEdit = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        harga_jualEdit = new javax.swing.JTextField();
        btn_clearEdit = new javax.swing.JButton();
        btn_simpanEdit = new javax.swing.JButton();
        btn_cancelEdit = new javax.swing.JButton();
        kode_barangLama = new javax.swing.JLabel();
        namaBarangLama = new javax.swing.JLabel();
        supplierLama = new javax.swing.JLabel();
        kategori_lama = new javax.swing.JLabel();
        stok_lama = new javax.swing.JLabel();
        harga_jualLama = new javax.swing.JLabel();
        harga_beliLama = new javax.swing.JLabel();
        rusak_lama = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_stokEdit = new javax.swing.JTextField();
        label_stokEdit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(239, 240, 245));

        navigasiPanel.setPreferredSize(new java.awt.Dimension(1026, 82));

        label_navigasi.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        label_navigasi.setText("Barang > Tambah Barang");
        label_navigasi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_navigasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_navigasiMouseClicked(evt);
            }
        });

        id_transaksi.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        id_transaksi.setForeground(new java.awt.Color(90, 90, 90));
        id_transaksi.setText("ID TRANSAKSI : ");

        labelTransaksi.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        labelTransaksi.setForeground(new java.awt.Color(90, 90, 90));
        labelTransaksi.setText("ID TRANSAKSI : ");

        txt_barangRusak.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        barang_RusakEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        total_stok.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout navigasiPanelLayout = new javax.swing.GroupLayout(navigasiPanel);
        navigasiPanel.setLayout(navigasiPanelLayout);
        navigasiPanelLayout.setHorizontalGroup(
            navigasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigasiPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(label_navigasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(51, 51, 51)
                .addComponent(total_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(barang_RusakEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_barangRusak, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175)
                .addComponent(labelTransaksi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id_transaksi)
                .addGap(22, 22, 22))
        );
        navigasiPanelLayout.setVerticalGroup(
            navigasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigasiPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(navigasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_navigasi, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(labelTransaksi)
                    .addComponent(id_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_barangRusak, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barang_RusakEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        MainConten.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setText("Kode Barang");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setText("Supplier");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setText("Nama Barang");

        txt_kodeBarang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txt_nama_barang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel5.setText("Total Stok");

        txt_stok.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel6.setText("Di Tambahkan pada");

        txt_addAt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel7.setText("Kategori");

        combo_kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_kategoriActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel8.setText("Harga Beli");

        txt_hargaBeli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel9.setText("Harga Jual");

        txt_hargaJual.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jButton1.setBackground(new java.awt.Color(96, 96, 96));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Clear");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        btn_simpanAdd.setBackground(new java.awt.Color(111, 59, 160));
        btn_simpanAdd.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btn_simpanAdd.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpanAdd.setText("Bayar");
        btn_simpanAdd.setPreferredSize(new java.awt.Dimension(73, 27));
        btn_simpanAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpanAddMouseClicked(evt);
            }
        });
        btn_simpanAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanAddActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 45, 45));
        jButton3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Cancel");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout contenAddBarangLayout = new javax.swing.GroupLayout(contenAddBarang);
        contenAddBarang.setLayout(contenAddBarangLayout);
        contenAddBarangLayout.setHorizontalGroup(
            contenAddBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenAddBarangLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(contenAddBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addGroup(contenAddBarangLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kode_brg_lama)
                        .addGap(44, 44, 44))
                    .addComponent(txt_nama_barang)
                    .addComponent(combo_supplier, 0, 250, Short.MAX_VALUE)
                    .addComponent(txt_kodeBarang))
                .addGap(72, 72, 72)
                .addGroup(contenAddBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(txt_stok)
                    .addComponent(txt_addAt)
                    .addComponent(combo_kategori, 0, 250, Short.MAX_VALUE))
                .addGap(67, 67, 67)
                .addGroup(contenAddBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contenAddBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(txt_hargaBeli, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(txt_hargaJual))
                    .addGroup(contenAddBarangLayout.createSequentialGroup()
                        .addComponent(btn_simpanAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        contenAddBarangLayout.setVerticalGroup(
            contenAddBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenAddBarangLayout.createSequentialGroup()
                .addGroup(contenAddBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenAddBarangLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(contenAddBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(contenAddBarangLayout.createSequentialGroup()
                                .addGroup(contenAddBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(kode_brg_lama))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_kodeBarang))
                            .addGroup(contenAddBarangLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contenAddBarangLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_hargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(contenAddBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenAddBarangLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(11, 11, 11)
                                .addComponent(txt_nama_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenAddBarangLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_hargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(contenAddBarangLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_addAt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(contenAddBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenAddBarangLayout.createSequentialGroup()
                        .addGroup(contenAddBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(contenAddBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combo_supplier, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(combo_kategori)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenAddBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_simpanAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101))
        );

        MainConten.add(contenAddBarang, "card2");

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel11.setText("Kode Barang");

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel12.setText("Supplier");

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel13.setText("Nama Barang");

        kode_barang_Edit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        nama_barangEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel15.setText("Di Ubah pada");

        update_atEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel16.setText("Kategori");

        kategori_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kategori_editMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kategori_editMouseEntered(evt);
            }
        });
        kategori_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategori_editActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel17.setText("Harga Beli");

        harga_beliEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel18.setText("Harga Jual");

        harga_jualEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btn_clearEdit.setBackground(new java.awt.Color(96, 96, 96));
        btn_clearEdit.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btn_clearEdit.setForeground(new java.awt.Color(255, 255, 255));
        btn_clearEdit.setText("Clear");
        btn_clearEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_clearEditMouseClicked(evt);
            }
        });

        btn_simpanEdit.setBackground(new java.awt.Color(111, 59, 160));
        btn_simpanEdit.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btn_simpanEdit.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpanEdit.setText("Simpan");
        btn_simpanEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpanEditMouseClicked(evt);
            }
        });
        btn_simpanEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanEditActionPerformed(evt);
            }
        });

        btn_cancelEdit.setBackground(new java.awt.Color(51, 45, 45));
        btn_cancelEdit.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btn_cancelEdit.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelEdit.setText("Cancel");
        btn_cancelEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cancelEditMouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel20.setText("Stok ");

        txt_stokEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout contenEditBarangLayout = new javax.swing.GroupLayout(contenEditBarang);
        contenEditBarang.setLayout(contenEditBarangLayout);
        contenEditBarangLayout.setHorizontalGroup(
            contenEditBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenEditBarangLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(contenEditBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenEditBarangLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(namaBarangLama)
                        .addGap(16, 16, 16))
                    .addGroup(contenEditBarangLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(supplierLama)
                        .addGap(22, 22, 22))
                    .addGroup(contenEditBarangLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kode_barangLama)
                        .addGap(17, 17, 17))
                    .addComponent(nama_barangEdit)
                    .addComponent(supplier_edit, 0, 254, Short.MAX_VALUE)
                    .addComponent(kode_barang_Edit))
                .addGroup(contenEditBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenEditBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(contenEditBarangLayout.createSequentialGroup()
                            .addGap(290, 290, 290)
                            .addComponent(stok_lama)
                            .addGap(85, 85, 85))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenEditBarangLayout.createSequentialGroup()
                            .addGap(72, 72, 72)
                            .addComponent(kategori_lama)
                            .addGap(111, 111, 111)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenEditBarangLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contenEditBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contenEditBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenEditBarangLayout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addGap(183, 183, 183))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenEditBarangLayout.createSequentialGroup()
                                    .addComponent(update_atEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)))
                            .addGroup(contenEditBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(kategori_edit, 0, 250, Short.MAX_VALUE)
                                .addComponent(jLabel15)
                                .addComponent(txt_stokEdit))
                            .addComponent(jLabel20))))
                .addGroup(contenEditBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenEditBarangLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(harga_beliLama))
                    .addGroup(contenEditBarangLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(rusak_lama))
                    .addGroup(contenEditBarangLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(contenEditBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(harga_jualEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(harga_beliEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenEditBarangLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btn_simpanEdit)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cancelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_clearEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenEditBarangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(harga_jualLama)
                .addGap(86, 86, 86))
        );
        contenEditBarangLayout.setVerticalGroup(
            contenEditBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenEditBarangLayout.createSequentialGroup()
                .addGroup(contenEditBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenEditBarangLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(contenEditBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contenEditBarangLayout.createSequentialGroup()
                                .addGroup(contenEditBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(contenEditBarangLayout.createSequentialGroup()
                                        .addGroup(contenEditBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(kode_barangLama, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(kode_barang_Edit)
                                        .addGap(18, 18, 18))
                                    .addGroup(contenEditBarangLayout.createSequentialGroup()
                                        .addComponent(harga_beliLama)
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(harga_beliEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)))
                                .addComponent(harga_jualLama))
                            .addGroup(contenEditBarangLayout.createSequentialGroup()
                                .addComponent(stok_lama)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_stokEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(contenEditBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenEditBarangLayout.createSequentialGroup()
                                .addGroup(contenEditBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(contenEditBarangLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(11, 11, 11))
                                    .addGroup(contenEditBarangLayout.createSequentialGroup()
                                        .addComponent(namaBarangLama)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addComponent(nama_barangEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenEditBarangLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(harga_jualEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(contenEditBarangLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(update_atEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(contenEditBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contenEditBarangLayout.createSequentialGroup()
                        .addGroup(contenEditBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(kategori_lama))
                        .addGap(18, 18, 18)
                        .addGroup(contenEditBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(supplier_edit, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(kategori_edit)))
                    .addGroup(contenEditBarangLayout.createSequentialGroup()
                        .addGroup(contenEditBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(supplierLama)
                            .addComponent(rusak_lama)
                            .addComponent(jLabel16))
                        .addGap(11, 11, 11)
                        .addGroup(contenEditBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_clearEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cancelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_simpanEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(101, 101, 101))
        );

        MainConten.add(contenEditBarang, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(navigasiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_stokEdit)
                .addGap(396, 396, 396))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(MainConten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(29, 29, 29)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(navigasiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(56, 56, 56)
                .addComponent(label_stokEdit)
                .addGap(424, 424, 424))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(132, 132, 132)
                    .addComponent(MainConten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(49, 49, 49)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void Action(String opsi){
  
        if(opsi.equals("add")){
            MainConten.removeAll();
            MainConten.add(contenAddBarang);
            MainConten.repaint();
            MainConten.revalidate();
            label_navigasi.setText("Barang > Tambah Barang");
            this.setTitle("Tambah Barang");
            txt_addAt.setText( Timestamp.valueOf(LocalDateTime.now()).toString()); 
            this.setVisible(true);
        }else if(opsi.equals("edit")){
            MainConten.removeAll();
            MainConten.add(contenEditBarang);
            MainConten.repaint();
            MainConten.revalidate();
            label_navigasi.setText("Barang > Edit Barang");
            this.setTitle("Edit Barang");
            this.setVisible(true);
        }
    }
    private void btn_simpanAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_simpanAddActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3MouseClicked

    private void label_navigasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_navigasiMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_label_navigasiMouseClicked

    private void btn_simpanEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_simpanEditActionPerformed

    private void btn_cancelEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelEditMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_cancelEditMouseClicked

    private void combo_kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_kategoriActionPerformed
         // TODO add your handling code here:
         
         String kode="";
         barangService br = new barangService();
         //set value kode tidak terlihat
         kode_brg_lama.setText(br.getIdBarang(true, kode, combo_kategori));
         //set value kode barang dengan value kode tidak terliht
         txt_kodeBarang.setText(kode_brg_lama.getText());
         // invisible kode barang lama
         kode_brg_lama.setVisible(false);
         // membuat field tidak bisa di rubah
         txt_kodeBarang.setEnabled(false);
    }//GEN-LAST:event_combo_kategoriActionPerformed

    private void btn_simpanAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanAddMouseClicked
           // TODO add your handling code here:
         //nama_produt.equals("")||harga_beli.equals("")||harga_jual.equals("")||stok.equals("")||stok.equals("0")
         //instansiate object
         DatabaseInterface dt = new Database();
         barangService br = new barangService();

         String kode="";
         boolean addBarang=false;
         String kata ="";
         //set value pada masing masing atribut dibawah
       
         String nama_product =txt_nama_barang.getText();
         String kode_product =txt_kodeBarang.getText();
         String hargaBeli =txt_hargaBeli.getText();
         String hargaJual =txt_hargaJual.getText();
         String stok =txt_stok.getText();
         String barangRusak =txt_barangRusak.getText();
          
        
         
         //Instansiasi object 
         SupplierInterface sup = new Supplier();
         KategoriInterface kt = new Kategori();
         //memberikan nilai pada suplier dan kategori berdasarkan value pada combobox
         String supplier = sup.getKodeSupplier(combo_supplier) ;
         String kategori = kt.getCodeKategori(combo_kategori);

         
         // sql untuk mendapatkan kode kategori dan supplier
         String sqlSupplier = "select kode_supplier from supplier where nama_supplier = ?";
         String sqlKategori ="select kode_kategori from kategori where nama_kategori = ? ";
         
         //try untuk memberikan supplier dengan kode supplier
         try(Connection conn = dt.conectDatabase();
                 PreparedStatement pst =conn.prepareStatement(sqlSupplier);
             ){
             
             pst.setString(1, combo_supplier.getSelectedItem().toString());
             ResultSet res = pst.executeQuery();
             if(res.next()){
                 
                 supplier = res.getString("kode_supplier");
                
              }

         }catch(SQLException e){
             System.out.println(e.getMessage());
         }
         //try untuk memberikan nilai kategori dengan kode kategori
         try(Connection conn = dt.conectDatabase();
                 PreparedStatement pst =conn.prepareStatement(sqlKategori);
                 ){
             
             pst.setString(1, combo_kategori.getSelectedItem().toString());
             ResultSet res = pst.executeQuery();
             if(res.next()){
                 
                 kategori = res.getString("kode_kategori");
               
             }    
            
         }catch(SQLException e){
             System.out.println(e.getMessage());
         }
       
  
         
         //jika semua kosong error
         if(nama_product.equals("")&&stok.equals("")&&hargaBeli.equals("")&&hargaJual.equals("")&&barangRusak.equals("0")){
             kata="Harap isi field dengan benar";
             addBarang=false;
         }
         //data tidak kosong semua
         else{
             String stokString =stok.replaceAll("[0-9]", "");
             String harga_jualS =hargaJual.replaceAll("[0-9]", "");
             String harga_beliS =hargaBeli.replaceAll("[0-9]", "");
             //stok tidak di isi dengan angka
             if(stok.equals(stokString)){
               kata="Harap isi stok dengan angka !";  
               addBarang=false;
             }
             //harga jual tidak diisi dengan angka
             else if(hargaJual.equals(harga_jualS)){
               kata="Harap isi harga Jual dengan angka !";
               addBarang=false;
             }
             //harga beli tidak diisi dengan angka
             else if(hargaBeli.equals(harga_beliS)){
                 kata="Harap isi harga Beli dengan angka !";
                 addBarang=false;    
             }
             //masuk ke kondisi kedua
             else{
                 
                 int hargaJualInt = Integer.parseInt(hargaJual.replaceAll("[^0-9]", ""));
                 int hargaBeliInt = Integer.parseInt(hargaBeli.replaceAll("[^0-9]", ""));
                 //jika harga jual lebih kecil
                 if(hargaJualInt<=hargaBeliInt){
                     kata="Harga Jual tidak memungkinkan input ulang !";
                     addBarang=false;
                 }else{
                 //jika semua validasi lolos maka true
                     addBarang=true;
                 }
             }
         }

         //alur jika true
         if(addBarang==true){
            this.setVisible(false);
            KonfirmasiBayarSupplier bayar = new KonfirmasiBayarSupplier();
          
            bayar.setSupp(supplier);
            bayar.setKat(kategori);
            bayar.setLabel_hargaBeli(hargaBeli);
            bayar.setLabel_hargaJual(hargaJual);
            bayar.setLabel_kodeProduct(kode_product);
            bayar.setLabel_namaProduct(nama_product);
            bayar.setLabel_rusak(barangRusak);
            bayar.setLabel_stok(stok);
            int hargaB =Integer.parseInt(hargaBeli.replaceAll("[^0-9]", ""));
            int stokB = Integer.parseInt(stok.replaceAll("[^0-9]", ""));
            
            int finalTotalInt = hargaB*stokB;
            String resultTotal = String.valueOf(finalTotalInt);
            
            
//            br.insertIdTransaksiBeli(id_transaksi.getText(), supplier, txt_addAt.getText(), kategori ,resultTotal);
//         
//         
//         
             
            bayar.setIdTransaksi(this.id_transaksi.getText().toString());
            bayar.setSubTotal(resultTotal);
            
            // bayar.setTotal();
           // this.dispose();
            bayar.action();
         

         }else{
            JOptionPane.showMessageDialog(null, kata, "Terjadi Kesalahan !", JOptionPane.ERROR_MESSAGE, eroricon);     

         }
      
        
        
   
    }//GEN-LAST:event_btn_simpanAddMouseClicked

    
    public void setTransaksi(String kode){
        this.id_transaksi.setText(kode);
    }
    private void btn_simpanEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanEditMouseClicked
          // TODO add your handling code here:
          
        
      barangService br = new barangService();
      
      String kode_brg=kode_barangLama.getText();
    
      String nama_product =nama_barangEdit.getText().toString();
     
          
        barangService barang = new barangService();
        String result =barang.getIdBarang(true, "", kategori_edit);
        
        if(nama_barangEdit.getText().equals("")||total_stok.getText().equals("")||harga_beliEdit.getText().equals("")||harga_jualEdit.getText().equals("")){
           JOptionPane.showMessageDialog(null, "Harap isi semua field terlebih dahulu" , "Terjadi kesalahan" ,JOptionPane.ERROR_MESSAGE);
            
        }else{
           
            int harga_beli =Integer.parseInt(harga_beliEdit.getText().toString().replaceAll("[^a-zA-Z0-9]", "").replaceAll("[a-zA-Z]", ""));
            int harga_jual=Integer.parseInt(harga_jualEdit.getText().toString().replaceAll("[^a-zA-Z0-9]", "").replaceAll("[a-zA-Z]", "")); 
            
            if(kode_barang_Edit.getText().toString().equals(kode_barangLama.getText().toString())&&nama_barangEdit.getText().toString().equals(namaBarangLama.getText())&&total_stok.getText().toString().equals(stok_lama.getText())&&harga_beliEdit.getText().toString().equals(harga_beliLama.getText())&&harga_jualEdit.getText().toString().equals(harga_jualLama.getText())&&barang_RusakEdit.getText().toString().equals(rusak_lama.getText().toString())&&kategori_edit.getSelectedItem().toString().equals(kategori_lama.getText())&&supplier_edit.getSelectedItem().toString().equals(supplierLama.getText())&&txt_stokEdit.getText().toString().equals(label_stokEdit.getText())&&kategori_edit.getSelectedItem().toString().equals(kategori_lama.getText().toString())&&nama_barangEdit.getText().equals(namaBarangLama.getText().toString())){
//                 kode_barang_Edit.setText(this.getKodeLama());
                
                 JOptionPane.showMessageDialog(null, "Tidak Ada Perubahan Data, Data Sudah terbaru", "Information", JOptionPane.INFORMATION_MESSAGE);
                 int stok =Integer.parseInt(txt_stokEdit.getText().toString().replaceAll("[^a-zA-Z0-9]", "").replaceAll("[a-zA-Z]", ""));
                 int rusak =Integer.parseInt(barang_RusakEdit.getText().toString().replaceAll("[^a-zA-Z0-9]", "").replaceAll("[a-zA-Z]", ""));
                 
             
               
                 br.editBarang(kode_brg, nama_product, stok, harga_beli, harga_jual, rusak,  kategori_edit, supplier_edit,this,kode_barang_Edit.getText().toString(),false);

        }else if(nama_barangEdit.getText().toString().equals("")||nama_barangEdit.getText().toString().equals("".replace("", " "))){
                      JOptionPane.showMessageDialog(null, "Field Nama barang harus di isi ! ", "Information", JOptionPane.INFORMATION_MESSAGE); 
                      int stok =Integer.parseInt(txt_stokEdit.getText().toString().replaceAll("[^a-zA-Z0-9]", "").replaceAll("[a-zA-Z]", ""));
               
        }else if(txt_stokEdit.getText().toString().equals("")){
                      JOptionPane.showMessageDialog(null, "Stok Tidak Memenuhi Syarat input ulang !", "Information", JOptionPane.INFORMATION_MESSAGE); 
                                  txt_stokEdit.setText(label_stokEdit.getText().toString());
                                  int stok =Integer.parseInt(txt_stokEdit.getText().toString().replaceAll("[^a-zA-Z0-9]", "").replaceAll("[a-zA-Z]", ""));
               
        }else if(barang_RusakEdit.getText().toString().equals("")||barang_RusakEdit.getText().toString().equals("".replace("", " "))){
                      JOptionPane.showMessageDialog(null, "Input Barang Rusak Tidak memenuhi syarat!", "Information", JOptionPane.INFORMATION_MESSAGE); 
                      int stok =Integer.parseInt(txt_stokEdit.getText().toString().replaceAll("[^a-zA-Z0-9]", "").replaceAll("[a-zA-Z]", ""));
                
        }
                       else{
                       int stok =Integer.parseInt(txt_stokEdit.getText().toString().replaceAll("[^a-zA-Z0-9]", "").replaceAll("[a-zA-Z]", ""));
                       int rusak =Integer.parseInt(barang_RusakEdit.getText().toString().replaceAll("[^a-zA-Z0-9]", "").replaceAll("[a-zA-Z]", ""));
                       Barang brangId = new Barang();
                       String kode_baru= brangId.getIdEdit(true, "", kategori_edit);
                       
                       if(kategori_edit.getSelectedItem().toString().equals(kategori_lama.getText().toString())){
                       br.editBarang(kode_brg, nama_product, stok, harga_beli, harga_jual, rusak,  kategori_edit, supplier_edit,this,kode_barangLama.getText().toString(),true);
 
                       }else{
                       br.editBarang(kode_brg, nama_product, stok, harga_beli, harga_jual, rusak,  kategori_edit, supplier_edit,this,kode_baru,true);
                       br.showBarang(Dashbord.table_barang);
                       }
                  br.showBarang(Dashbord.table_barang);    
                    
        }
        }
     
        
      
     
    
    }//GEN-LAST:event_btn_simpanEditMouseClicked

    private void kategori_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kategori_editMouseClicked
         // TODO add your handling code here:
         
     
    }//GEN-LAST:event_kategori_editMouseClicked

    private void kategori_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategori_editActionPerformed
         // TODO add your handling code here:
    
    
    
         
   
    }//GEN-LAST:event_kategori_editActionPerformed

    private void kategori_editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kategori_editMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_kategori_editMouseEntered

    private void btn_clearEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clearEditMouseClicked
         // TODO add your handling code here:
         
         this.nama_barangEdit.setText("");
         this.harga_beliEdit.setText("");
         this.harga_jualEdit.setText("");
         this.txt_stokEdit.setText("");
         this.barang_RusakEdit.setText("0");
//         this.total_stok.setText("");
      
    }//GEN-LAST:event_btn_clearEditMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
         // TODO add your handling code here:
         
         this.total_stok.setText("");
         this.txt_nama_barang.setText("");
         this.txt_hargaJual.setText("");
         this.txt_hargaBeli.setText("");
         this.txt_stok.setText("");
         
    }//GEN-LAST:event_jButton1MouseClicked

    
    
    public void setKodeLama(String kode){
        
        kode_barangLama.setText(kode.toUpperCase());
        
        
       
    }
    
    public String getKodeLama(){
        return kode_barangLama.getText();
    }
    
    public void editBarang(String opsi,String kode ){
        
         DatabaseInterface dt = new Database();
         tanggalSaatIni tg = new tanggalSaatIni();
         supplierService su = new supplierService();
         barangService br = new barangService();
         BarangInterface bra= new Barang();
         if(opsi.equals("edit")){
            String sql ="select * from product where kode_product='"+kode_barangLama.getText()+"'";
             
            try (Connection con = dt.conectDatabase();
                Statement st = con.createStatement();
                ResultSet res = st.executeQuery(sql)){
               
                while(res.next()){
                    kode_barang_Edit.setText(kode);
                    kode_barangLama.setText(kode);
                    nama_barangEdit.setText(res.getString("nama_product"));
                    namaBarangLama.setText(res.getString("nama_product"));
                    total_stok.setText(res.getString("total_stok"));
                    stok_lama.setText(res.getString("total_stok"));
                    txt_stokEdit.setText(res.getString("stok"));
                    update_atEdit.setText(tg.getCurrentTimeStamp());
                    harga_beliEdit.setText(res.getString("harga_beli")); 
                    harga_beliLama.setText(res.getString("harga_beli"));
                    harga_jualEdit.setText(res.getString("harga_jual"));
                    harga_jualLama.setText(res.getString("harga_jual"));
                    barang_RusakEdit.setText(res.getString("rusak"));
                    label_stokEdit.setText(res.getString("stok"));
                    rusak_lama.setText(res.getString("rusak"));
                    

                      String sqlKat ="select nama_kategori from kategori where kode_kategori =?";
                      String sqlsup ="select nama_supplier from supplier where kode_supplier =?";
                    
                    
                    try(Connection conKat = dt.conectDatabase();
                        PreparedStatement pst = conKat.prepareStatement(sqlKat) ){{
                        pst.setString(1, res.getString("kategori"));
                        ResultSet resKat = pst.executeQuery();
                        while(resKat.next()){
                            kategori_edit.setSelectedItem(resKat.getString("nama_kategori"));
                            kategori_lama.setText(resKat.getString("nama_kategori"));
//                            br.addItemInCombobox(kategori_edit);
                           
                        }    
                        }
                        
                     try(Connection conSup =dt.conectDatabase();
                         PreparedStatement pstSup =conSup.prepareStatement(sqlsup);
                        ){
                         pstSup.setString(1, res.getString("supplier"));
                         ResultSet resSup = pstSup.executeQuery();
                         
                         while (resSup.next())
                         {
                             supplier_edit.setSelectedItem(resSup.getString("nama_supplier"));
                             supplierLama.setText(resSup.getString("nama_supplier"));
//                             su.addItemSupplier(supplier_edit);
                         }
                         }   
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            
            
            
            
            
        }
        
        
        
        
        
        
        
    }
  
    /**
     * @param args the command line arguments 
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataBarangTambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataBarangTambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataBarangTambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataBarangTambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataBarangTambah().setVisible(true);
            }
        });
    }
    
    class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
        
        
    }
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainConten;
    private javax.swing.JTextField barang_RusakEdit;
    private javax.swing.JButton btn_cancelEdit;
    private javax.swing.JButton btn_clearEdit;
    private javax.swing.JButton btn_simpanAdd;
    private javax.swing.JButton btn_simpanEdit;
    public static javax.swing.JComboBox<String> combo_kategori;
    public static javax.swing.JComboBox<String> combo_supplier;
    private javax.swing.JPanel contenAddBarang;
    private javax.swing.JPanel contenEditBarang;
    private javax.swing.JTextField harga_beliEdit;
    private javax.swing.JLabel harga_beliLama;
    private javax.swing.JTextField harga_jualEdit;
    private javax.swing.JLabel harga_jualLama;
    public static javax.swing.JLabel id_transaksi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JComboBox<String> kategori_edit;
    private javax.swing.JLabel kategori_lama;
    private javax.swing.JLabel kode_barangLama;
    public static javax.swing.JTextField kode_barang_Edit;
    private javax.swing.JLabel kode_brg_lama;
    public static javax.swing.JLabel labelTransaksi;
    private javax.swing.JLabel label_navigasi;
    private javax.swing.JLabel label_stokEdit;
    private javax.swing.JLabel namaBarangLama;
    private javax.swing.JTextField nama_barangEdit;
    private javax.swing.JPanel navigasiPanel;
    private javax.swing.JLabel rusak_lama;
    private javax.swing.JLabel stok_lama;
    private javax.swing.JLabel supplierLama;
    private javax.swing.JComboBox<String> supplier_edit;
    private javax.swing.JTextField total_stok;
    private javax.swing.JTextField txt_addAt;
    public static javax.swing.JTextField txt_barangRusak;
    public static javax.swing.JTextField txt_hargaBeli;
    public static javax.swing.JTextField txt_hargaJual;
    public static javax.swing.JTextField txt_kodeBarang;
    public static javax.swing.JTextField txt_nama_barang;
    public static javax.swing.JTextField txt_stok;
    private javax.swing.JTextField txt_stokEdit;
    private javax.swing.JTextField update_atEdit;
    // End of variables declaration//GEN-END:variables
}
