/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author user
 */
public class dataTambahReturn extends javax.swing.JFrame {

    /**
     * Creates new form dataTambahReturn
     */
   
    public dataTambahReturn() {
        initComponents();
        
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNavigasi = new RoundedPanel(8, new Color(255, 255, 255));
        label_navigasi = new javax.swing.JLabel();
        MainConten = new RoundedPanel(8, new Color(255, 255, 255));
        returnEdit = new RoundedPanel(8, new Color(255, 255, 255));
        jLabel8 = new javax.swing.JLabel();
        kode_barangReturn = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nama_barangReturn = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jumlah_barangRusak = new javax.swing.JTextField();
        simpan_editReturn = new javax.swing.JButton();
        btn_cancelEditReturn = new javax.swing.JButton();
        btn_clearReturn = new javax.swing.JButton();
        statusReturn = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        returnTambah = new RoundedPanel(8, new Color(255, 255, 255));
        jLabel2 = new javax.swing.JLabel();
        kode_addReturn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nama_barangReturnAdd = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jumlahReturnAdd = new javax.swing.JTextField();
        btn_simpanAddReturn = new javax.swing.JButton();
        btn_cancelAddreturn = new javax.swing.JButton();
        btn_clearAddreturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelNavigasi.setPreferredSize(new java.awt.Dimension(519, 68));

        label_navigasi.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        label_navigasi.setText("Barang Return > Tambah Return");

        javax.swing.GroupLayout panelNavigasiLayout = new javax.swing.GroupLayout(panelNavigasi);
        panelNavigasi.setLayout(panelNavigasiLayout);
        panelNavigasiLayout.setHorizontalGroup(
            panelNavigasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavigasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_navigasi)
                .addContainerGap(275, Short.MAX_VALUE))
        );
        panelNavigasiLayout.setVerticalGroup(
            panelNavigasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavigasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_navigasi, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainConten.setLayout(new java.awt.CardLayout());

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(90, 90, 90));
        jLabel8.setText("Kode Barang");

        kode_barangReturn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(90, 90, 90));
        jLabel9.setText("Nama Barang");

        nama_barangReturn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(90, 90, 90));
        jLabel10.setText("Jumlah Barang");

        jumlah_barangRusak.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        simpan_editReturn.setBackground(new java.awt.Color(111, 59, 160));
        simpan_editReturn.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        simpan_editReturn.setForeground(new java.awt.Color(255, 255, 255));
        simpan_editReturn.setText("Simpan");
        simpan_editReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_editReturnActionPerformed(evt);
            }
        });

        btn_cancelEditReturn.setBackground(new java.awt.Color(51, 45, 45));
        btn_cancelEditReturn.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btn_cancelEditReturn.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelEditReturn.setText("Cancel");
        btn_cancelEditReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cancelEditReturnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cancelEditReturnMouseEntered(evt);
            }
        });
        btn_cancelEditReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelEditReturnActionPerformed(evt);
            }
        });

        btn_clearReturn.setBackground(new java.awt.Color(96, 96, 96));
        btn_clearReturn.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btn_clearReturn.setForeground(new java.awt.Color(255, 255, 255));
        btn_clearReturn.setText("Clear");
        btn_clearReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearReturnActionPerformed(evt);
            }
        });

        statusReturn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baik", "Masih Rusak" }));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(90, 90, 90));
        jLabel11.setText("Status");

        javax.swing.GroupLayout returnEditLayout = new javax.swing.GroupLayout(returnEdit);
        returnEdit.setLayout(returnEditLayout);
        returnEditLayout.setHorizontalGroup(
            returnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnEditLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(returnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(returnEditLayout.createSequentialGroup()
                        .addGroup(returnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(kode_barangReturn)
                            .addComponent(nama_barangReturn, 0, 250, Short.MAX_VALUE)
                            .addComponent(jumlah_barangRusak))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addGroup(returnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(simpan_editReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cancelEditReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_clearReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77))
                    .addGroup(returnEditLayout.createSequentialGroup()
                        .addGroup(returnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(statusReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        returnEditLayout.setVerticalGroup(
            returnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnEditLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel8)
                .addGap(11, 11, 11)
                .addGroup(returnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kode_barangReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpan_editReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(returnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama_barangReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelEditReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(returnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlah_barangRusak, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clearReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusReturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        MainConten.add(returnEdit, "card2");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(90, 90, 90));
        jLabel2.setText("Kode Barang");

        kode_addReturn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(90, 90, 90));
        jLabel3.setText("Nama Barang");

        nama_barangReturnAdd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(90, 90, 90));
        jLabel4.setText("Jumlah Barang");

        jumlahReturnAdd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btn_simpanAddReturn.setBackground(new java.awt.Color(111, 59, 160));
        btn_simpanAddReturn.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btn_simpanAddReturn.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpanAddReturn.setText("Simpan");
        btn_simpanAddReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanAddReturnActionPerformed(evt);
            }
        });

        btn_cancelAddreturn.setBackground(new java.awt.Color(51, 45, 45));
        btn_cancelAddreturn.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btn_cancelAddreturn.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelAddreturn.setText("Cancel");
        btn_cancelAddreturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cancelAddreturnMouseClicked(evt);
            }
        });
        btn_cancelAddreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelAddreturnActionPerformed(evt);
            }
        });

        btn_clearAddreturn.setBackground(new java.awt.Color(96, 96, 96));
        btn_clearAddreturn.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btn_clearAddreturn.setForeground(new java.awt.Color(255, 255, 255));
        btn_clearAddreturn.setText("Clear");
        btn_clearAddreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearAddreturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout returnTambahLayout = new javax.swing.GroupLayout(returnTambah);
        returnTambah.setLayout(returnTambahLayout);
        returnTambahLayout.setHorizontalGroup(
            returnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnTambahLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(returnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(kode_addReturn)
                    .addComponent(nama_barangReturnAdd, 0, 250, Short.MAX_VALUE)
                    .addComponent(jumlahReturnAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(returnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_simpanAddReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelAddreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clearAddreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );
        returnTambahLayout.setVerticalGroup(
            returnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnTambahLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addGroup(returnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kode_addReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_simpanAddReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(returnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama_barangReturnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelAddreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(returnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlahReturnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clearAddreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        MainConten.add(returnTambah, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(panelNavigasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(MainConten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(29, 29, 29)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelNavigasi, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(417, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(98, Short.MAX_VALUE)
                    .addComponent(MainConten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(33, 33, 33)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void Action(String opsi){
        if(opsi.equals("edit")){
            MainConten.removeAll();
            MainConten.add(returnEdit);
            MainConten.repaint();
            MainConten.revalidate();
            label_navigasi.setText("Barang Return > Edit return");
            this.setVisible(true);
        }else if(opsi.equals("add")){
            MainConten.removeAll();
            MainConten.add(returnTambah);
            MainConten.repaint();
            MainConten.revalidate();
            label_navigasi.setText("Barang Return > Tambah return");
            this.setVisible(true);
        }
    }
    private void btn_simpanAddReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanAddReturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_simpanAddReturnActionPerformed

    private void btn_cancelAddreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelAddreturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelAddreturnActionPerformed

    private void btn_clearAddreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearAddreturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_clearAddreturnActionPerformed

    private void simpan_editReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_editReturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simpan_editReturnActionPerformed

    private void btn_cancelEditReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelEditReturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelEditReturnActionPerformed

    private void btn_clearReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearReturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_clearReturnActionPerformed

    private void btn_cancelAddreturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelAddreturnMouseClicked
         // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_btn_cancelAddreturnMouseClicked

    private void btn_cancelEditReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelEditReturnMouseEntered
         // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelEditReturnMouseEntered

    private void btn_cancelEditReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelEditReturnMouseClicked
         // TODO add your handling code here:4
         this.dispose();
    }//GEN-LAST:event_btn_cancelEditReturnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataTambahReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataTambahReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataTambahReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataTambahReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataTambahReturn().setVisible(true);
            }
        });
    }
    
    public class RoundJTextField extends JTextField {
    private Shape shape;
    public RoundJTextField(int size) {
        super(size);
        setOpaque(false); // As suggested by @AVD in comment.
    }
    protected void paintComponent(Graphics g) {
         g.setColor(getBackground());
         g.fillRoundRect(0, 0, getWidth()-1, getHeight()-1, 15, 15);
         super.paintComponent(g);
    }
    protected void paintBorder(Graphics g) {
         g.setColor(getForeground());
         g.drawRoundRect(0, 0, getWidth()-1, getHeight()-1, 15, 15);
    }
    public boolean contains(int x, int y) {
         if (shape == null || !shape.getBounds().equals(getBounds())) {
             shape = new RoundRectangle2D.Float(0, 0, getWidth()-1, getHeight()-1, 15, 15);
         }
         return shape.contains(x, y);
    }
}
    
     class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainConten;
    private javax.swing.JButton btn_cancelAddreturn;
    private javax.swing.JButton btn_cancelEditReturn;
    private javax.swing.JButton btn_clearAddreturn;
    private javax.swing.JButton btn_clearReturn;
    private javax.swing.JButton btn_simpanAddReturn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jumlahReturnAdd;
    private javax.swing.JTextField jumlah_barangRusak;
    private javax.swing.JTextField kode_addReturn;
    private javax.swing.JTextField kode_barangReturn;
    private javax.swing.JLabel label_navigasi;
    private javax.swing.JComboBox<String> nama_barangReturn;
    private javax.swing.JComboBox<String> nama_barangReturnAdd;
    private javax.swing.JPanel panelNavigasi;
    private javax.swing.JPanel returnEdit;
    private javax.swing.JPanel returnTambah;
    private javax.swing.JButton simpan_editReturn;
    private javax.swing.JComboBox<String> statusReturn;
    // End of variables declaration//GEN-END:variables
}
