/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Repository.Database;
import Repository.DatabaseInterface;
import Repository.Kategori;
import Repository.KategoriInterface;
import static View.Dashbord.tabel_kategori;
import static View.Dashbord.table_barang;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import service.barangService;
import service.kategoriService;

/**
 *
 * @author user
 */
public class DataTambahKategori extends javax.swing.JFrame {

    /**
     * Creates new form DataTambahKategori
     */
    
    //variable
    String kode_kategori;
    ImageIcon suscesicon =  new ImageIcon(getClass().getResource("/picture/checked.png"));
    ImageIcon eroricon =  new ImageIcon(getClass().getResource("/picture/warning.png"));
    String time = Timestamp.valueOf(LocalDateTime.now()).toString();

      kategoriService kategori = new kategoriService();
      
      public DataTambahKategori() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
     
        TXT_kategori.setText(kategori.getPrimaryKey());
        TXT_createAt.setText(time);
        TXT_kategori.setEnabled(false);
        TXT_createAt.setEnabled(false);
        TXT_kodeKategoriEdit.setEnabled(false);
        TXT_updateAtKategori.setEnabled(false);
        label_editNamaKategori.setVisible(false);
        
    }
    public void setKodeKategoriLama(String kode){
        this.kode_kategori =kode;
        
    }
    public String getKodeKategoriLama(){
        return this.kode_kategori;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new RoundedPanel(8, new Color(255,255,255));
        labelNavigasi = new javax.swing.JLabel();
        contenPanel = new RoundedPanel(8, new Color(255, 255, 255));
        conten_Add = new RoundedPanel(8, new Color(255, 255, 255));
        label_kodeKategori = new javax.swing.JLabel();
        TXT_kategori = new javax.swing.JTextField();
        label_namaKategori = new javax.swing.JLabel();
        TXT_namaKategori = new javax.swing.JTextField();
        label_createAtKategori = new javax.swing.JLabel();
        TXT_createAt = new javax.swing.JTextField();
        btn_simpanTambahKategori = new javax.swing.JButton();
        btn_cancelKategori = new javax.swing.JButton();
        btn_clearKategori = new javax.swing.JButton();
        conten_edit = new RoundedPanel(8, new Color(255, 255, 255));
        label_kodeKategoriEdit = new javax.swing.JLabel();
        TXT_kodeKategoriEdit = new javax.swing.JTextField();
        label_namaKategoriEdit = new javax.swing.JLabel();
        TXT_namaKategoriEdit = new javax.swing.JTextField();
        label_updateAtkategoriEdit = new javax.swing.JLabel();
        TXT_updateAtKategori = new javax.swing.JTextField();
        btn_simpanKategoriEdit = new javax.swing.JButton();
        brn_cancelEditKategori = new javax.swing.JButton();
        btn_clearEditKategori = new javax.swing.JButton();
        kode_lama = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        label_editNamaKategori = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelNavigasi.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        labelNavigasi.setText("Kategori > Tambah Kategori");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNavigasi)
                .addContainerGap(311, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNavigasi, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        contenPanel.setLayout(new java.awt.CardLayout());

        label_kodeKategori.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        label_kodeKategori.setText("Kode Kategori");

        TXT_kategori.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        label_namaKategori.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        label_namaKategori.setText("Nama Kategori");

        TXT_namaKategori.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        label_createAtKategori.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        label_createAtKategori.setText("Create at");

        TXT_createAt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btn_simpanTambahKategori.setBackground(new java.awt.Color(111, 59, 160));
        btn_simpanTambahKategori.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btn_simpanTambahKategori.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpanTambahKategori.setText("Simpan");
        btn_simpanTambahKategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpanTambahKategoriMouseClicked(evt);
            }
        });

        btn_cancelKategori.setBackground(new java.awt.Color(51, 45, 45));
        btn_cancelKategori.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btn_cancelKategori.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelKategori.setText("Cancel");
        btn_cancelKategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cancelKategoriMouseClicked(evt);
            }
        });

        btn_clearKategori.setBackground(new java.awt.Color(96, 96, 96));
        btn_clearKategori.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btn_clearKategori.setForeground(new java.awt.Color(255, 255, 255));
        btn_clearKategori.setText("Clear");
        btn_clearKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearKategoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout conten_AddLayout = new javax.swing.GroupLayout(conten_Add);
        conten_Add.setLayout(conten_AddLayout);
        conten_AddLayout.setHorizontalGroup(
            conten_AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conten_AddLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(conten_AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_createAtKategori)
                    .addComponent(label_namaKategori)
                    .addComponent(label_kodeKategori)
                    .addGroup(conten_AddLayout.createSequentialGroup()
                        .addGroup(conten_AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TXT_createAt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(TXT_namaKategori, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXT_kategori, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(84, 84, 84)
                        .addGroup(conten_AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_clearKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cancelKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_simpanTambahKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        conten_AddLayout.setVerticalGroup(
            conten_AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conten_AddLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(label_kodeKategori)
                .addGap(12, 12, 12)
                .addGroup(conten_AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(conten_AddLayout.createSequentialGroup()
                        .addComponent(TXT_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_namaKategori)
                        .addGap(12, 12, 12)
                        .addComponent(TXT_namaKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_createAtKategori)
                        .addGap(12, 12, 12)
                        .addComponent(TXT_createAt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(conten_AddLayout.createSequentialGroup()
                        .addComponent(btn_simpanTambahKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btn_cancelKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btn_clearKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        contenPanel.add(conten_Add, "card2");

        label_kodeKategoriEdit.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        label_kodeKategoriEdit.setText("Kode Kategori");

        TXT_kodeKategoriEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        label_namaKategoriEdit.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        label_namaKategoriEdit.setText("Nama Kategori");

        TXT_namaKategoriEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        label_updateAtkategoriEdit.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        label_updateAtkategoriEdit.setText("Update At");

        TXT_updateAtKategori.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btn_simpanKategoriEdit.setBackground(new java.awt.Color(111, 59, 160));
        btn_simpanKategoriEdit.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btn_simpanKategoriEdit.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpanKategoriEdit.setText("Simpan");
        btn_simpanKategoriEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpanKategoriEditMouseClicked(evt);
            }
        });

        brn_cancelEditKategori.setBackground(new java.awt.Color(51, 45, 45));
        brn_cancelEditKategori.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        brn_cancelEditKategori.setForeground(new java.awt.Color(255, 255, 255));
        brn_cancelEditKategori.setText("Cancel");
        brn_cancelEditKategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brn_cancelEditKategoriMouseClicked(evt);
            }
        });

        btn_clearEditKategori.setBackground(new java.awt.Color(96, 96, 96));
        btn_clearEditKategori.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btn_clearEditKategori.setForeground(new java.awt.Color(255, 255, 255));
        btn_clearEditKategori.setText("Clear");
        btn_clearEditKategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_clearEditKategoriMouseClicked(evt);
            }
        });
        btn_clearEditKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearEditKategoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout conten_editLayout = new javax.swing.GroupLayout(conten_edit);
        conten_edit.setLayout(conten_editLayout);
        conten_editLayout.setHorizontalGroup(
            conten_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conten_editLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(conten_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(conten_editLayout.createSequentialGroup()
                        .addComponent(label_kodeKategoriEdit)
                        .addGap(75, 75, 75)
                        .addComponent(kode_lama))
                    .addGroup(conten_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, conten_editLayout.createSequentialGroup()
                            .addComponent(label_namaKategoriEdit)
                            .addGroup(conten_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(conten_editLayout.createSequentialGroup()
                                    .addGap(77, 77, 77)
                                    .addComponent(jLabel1))
                                .addGroup(conten_editLayout.createSequentialGroup()
                                    .addGap(69, 69, 69)
                                    .addComponent(label_editNamaKategori)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                            .addComponent(brn_cancelEditKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(conten_editLayout.createSequentialGroup()
                            .addGroup(conten_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(conten_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TXT_updateAtKategori, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(TXT_namaKategoriEdit, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXT_kodeKategoriEdit, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(label_updateAtkategoriEdit))
                            .addGap(84, 84, 84)
                            .addGroup(conten_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btn_simpanKategoriEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_clearEditKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        conten_editLayout.setVerticalGroup(
            conten_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conten_editLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(conten_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_kodeKategoriEdit)
                    .addComponent(kode_lama))
                .addGap(12, 12, 12)
                .addGroup(conten_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(conten_editLayout.createSequentialGroup()
                        .addComponent(TXT_kodeKategoriEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(conten_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_namaKategoriEdit)
                            .addComponent(jLabel1)
                            .addComponent(label_editNamaKategori))
                        .addGap(12, 12, 12)
                        .addComponent(TXT_namaKategoriEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_updateAtkategoriEdit)
                        .addGap(12, 12, 12)
                        .addComponent(TXT_updateAtKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(conten_editLayout.createSequentialGroup()
                        .addComponent(btn_simpanKategoriEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(brn_cancelEditKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btn_clearEditKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        contenPanel.add(conten_edit, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(contenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(15, 15, 15)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(75, Short.MAX_VALUE)
                    .addComponent(contenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(33, 33, 33)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void Action(String opsi){
        if(opsi.equals("edit")){
            contenPanel.removeAll();
            contenPanel.add(conten_edit);
            contenPanel.repaint();
            contenPanel.revalidate();
            labelNavigasi.setText("Kategori > Edit Kategori");
            this.setTitle("Edit Kategori");
       
            this.setVisible(true);

        }else if(opsi.equals("add")){
            contenPanel.removeAll();
            contenPanel.add(conten_Add);
            contenPanel.repaint();
            contenPanel.revalidate();
            labelNavigasi.setText("Kategori > Tambah Kategori");
            this.setTitle("Tambah Kategori");
            this.setVisible(true);
        }
    }
    private void btn_clearKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_clearKategoriActionPerformed

    private void btn_cancelKategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelKategoriMouseClicked
         // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_btn_cancelKategoriMouseClicked

    private void brn_cancelEditKategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brn_cancelEditKategoriMouseClicked
        // TODO add your handling code here:
        this.dispose();
        TXT_kategori.setText("");
        TXT_namaKategori.setText("");
        TXT_createAt.setText("");
    }//GEN-LAST:event_brn_cancelEditKategoriMouseClicked

    private void btn_clearEditKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearEditKategoriActionPerformed
        // TODO add your handling code here:
        TXT_kategori.setText("");
        TXT_namaKategori.setText("");
        TXT_createAt.setText("");
    }//GEN-LAST:event_btn_clearEditKategoriActionPerformed

    private void btn_clearEditKategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clearEditKategoriMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_clearEditKategoriMouseClicked

    private void btn_simpanTambahKategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanTambahKategoriMouseClicked
         // TODO add your handling code here:
         String kode =  TXT_kategori.getText().toString();
         String name = TXT_namaKategori.getText().toString();
         
         kategoriService kategori = new kategoriService();
         if(kategori.addSupplier(name, kode, time)==true){
             JOptionPane.showMessageDialog(null, "Kamu harus Relogin untuk Merefresh Filter barang", "Succes", JOptionPane.INFORMATION_MESSAGE,suscesicon);
             this.dispose();
         }
         barangService br = new barangService();
         br.showBarang(table_barang);
         kategori.showKategori(Dashbord.tabel_kategori);
         
      
         
    }//GEN-LAST:event_btn_simpanTambahKategoriMouseClicked

    private void btn_simpanKategoriEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanKategoriEditMouseClicked
         // TODO add your handling code here:
         String nama_baru = TXT_namaKategoriEdit.getText().toString();
         String nama_lama = label_editNamaKategori.getText();
         System.out.println(nama_baru);
         System.out.println(nama_lama);
         kategoriService katSer = new kategoriService();
        
      
         kategori.editKategori(kode_kategori, nama_baru, nama_lama , this);
          katSer.showKategori(Dashbord.tabel_kategori);
         
    }//GEN-LAST:event_btn_simpanKategoriEditMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataTambahKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataTambahKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataTambahKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataTambahKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataTambahKategori().setVisible(true);
            }
        });
    }
    
    
    public void senEdit(String kode, String nama , String update){
        System.out.println("Kode "+getKodeKategoriLama());

        kategori.sendDataKategori(kode, nama, update);
      
        TXT_kodeKategoriEdit.setText(kode);
        TXT_namaKategoriEdit.setText(nama);
        TXT_updateAtKategori.setText(update);
    }
    
    public void editKategori(String opsi , String kode_kat){
        DatabaseInterface dt = new Database();
        String kode="";
        String nama_kategori="";
        if(opsi.equals("edit")){
            
      
            String sql ="select kode_kategori , nama_kategori , update_at from kategori where kode_kategori = '"+kode_kat+"'";
            try(Connection con = dt.conectDatabase();
            Statement st = con.createStatement();
            ResultSet res = st.executeQuery(sql)){
            
            if(res.next()){
                kode =res.getString("kode_kategori");
                nama_kategori =res.getString("nama_kategori");
            
                TXT_kodeKategoriEdit.setText(getKodeKategoriLama());
                TXT_namaKategoriEdit.setText(nama_kategori);
                TXT_updateAtKategori.setText(time);
                label_editNamaKategori.setText(nama_kategori);
                
            }
   
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Gagal Update Kategori"+e.getMessage(), "Terjadi Kesalahan", JOptionPane.INFORMATION_MESSAGE, eroricon);
        } 
            
            
            
            
            
        }
        
    }
    class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
        
        
    }
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXT_createAt;
    private javax.swing.JTextField TXT_kategori;
    private javax.swing.JTextField TXT_kodeKategoriEdit;
    private javax.swing.JTextField TXT_namaKategori;
    private javax.swing.JTextField TXT_namaKategoriEdit;
    private javax.swing.JTextField TXT_updateAtKategori;
    private javax.swing.JButton brn_cancelEditKategori;
    private javax.swing.JButton btn_cancelKategori;
    private javax.swing.JButton btn_clearEditKategori;
    private javax.swing.JButton btn_clearKategori;
    private javax.swing.JButton btn_simpanKategoriEdit;
    private javax.swing.JButton btn_simpanTambahKategori;
    private javax.swing.JPanel contenPanel;
    private javax.swing.JPanel conten_Add;
    private javax.swing.JPanel conten_edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel kode_lama;
    private javax.swing.JLabel labelNavigasi;
    private javax.swing.JLabel label_createAtKategori;
    private javax.swing.JLabel label_editNamaKategori;
    private javax.swing.JLabel label_kodeKategori;
    private javax.swing.JLabel label_kodeKategoriEdit;
    private javax.swing.JLabel label_namaKategori;
    private javax.swing.JLabel label_namaKategoriEdit;
    private javax.swing.JLabel label_updateAtkategoriEdit;
    // End of variables declaration//GEN-END:variables
}
