/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Repository.Database;
import Repository.DatabaseInterface;
import Repository.Supplier;
import Repository.SupplierInterface;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import service.supplierService;

/**
 *
 * @author user
 */
public class DataTambahSupplier extends javax.swing.JFrame {
    
    supplierService sup = new supplierService();
      String time ;
      String kode_supplier;
      ImageIcon eroricon =  new ImageIcon(getClass().getResource("/picture/warning.png"));


    /**
     * Creates new form DataTambahKategori
     */
    
    public JPanel getPanel(){
       return contenPanel;
    }
    
    public JPanel getContenAdd(){
        return conten_tambahPanel;
    }
    public JPanel getContenEdit(){
        return conten_editPanel; 
    }
    public DataTambahSupplier() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        txt_idSupplier.setText(sup.getKode());
        txt_idSupplier.setEnabled(false);
        time = Timestamp.valueOf(LocalDateTime.now()).toString();
        txt_createAtt.setText(time);
        txt_createAtt.setEnabled(false);
        id_supEdit.setEnabled(false);
        update_atEdit.setEnabled(false);
        this.nama_supLama.setVisible(false);
        this.setTitle("Tambah Supplier");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenPanel = new RoundedPanel(8, new Color(255, 255, 255));
        conten_tambahPanel = new RoundedPanel(8, new Color(255, 255, 255));
        jLabel2 = new javax.swing.JLabel();
        txt_idSupplier = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_nama_supplierAdd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_createAtt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        conten_editPanel = new RoundedPanel(8, new Color(255, 255, 255));
        jLabel5 = new javax.swing.JLabel();
        id_supEdit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        namaSup_edit = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        update_atEdit = new javax.swing.JTextField();
        btn_simpanEdit = new javax.swing.JButton();
        btn_cancelEdit = new javax.swing.JButton();
        btn_clearEdit = new javax.swing.JButton();
        nama_supLama = new javax.swing.JLabel();
        navigasi_panel = new RoundedPanel(8, new Color(255, 255, 255));
        label_Navigasi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        contenPanel.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setText("Id Supplier");

        txt_idSupplier.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setText("Nama Supplier");

        txt_nama_supplierAdd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setText("Create at");

        txt_createAtt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jButton1.setBackground(new java.awt.Color(111, 59, 160));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Simpan");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 45, 45));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancel");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(96, 96, 96));
        jButton3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Clear");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout conten_tambahPanelLayout = new javax.swing.GroupLayout(conten_tambahPanel);
        conten_tambahPanel.setLayout(conten_tambahPanelLayout);
        conten_tambahPanelLayout.setHorizontalGroup(
            conten_tambahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conten_tambahPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(conten_tambahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(conten_tambahPanelLayout.createSequentialGroup()
                        .addComponent(txt_createAtt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(conten_tambahPanelLayout.createSequentialGroup()
                        .addComponent(txt_nama_supplierAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))))
            .addGroup(conten_tambahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(conten_tambahPanelLayout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addGroup(conten_tambahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addGroup(conten_tambahPanelLayout.createSequentialGroup()
                            .addGroup(conten_tambahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_idSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addGap(84, 84, 84)
                            .addGroup(conten_tambahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(82, Short.MAX_VALUE)))
        );
        conten_tambahPanelLayout.setVerticalGroup(
            conten_tambahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, conten_tambahPanelLayout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addGroup(conten_tambahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nama_supplierAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(txt_createAtt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(conten_tambahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(conten_tambahPanelLayout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addComponent(jLabel2)
                    .addGap(12, 12, 12)
                    .addGroup(conten_tambahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(conten_tambahPanelLayout.createSequentialGroup()
                            .addComponent(txt_idSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel3)
                            .addGap(63, 63, 63)
                            .addComponent(jLabel4))
                        .addGroup(conten_tambahPanelLayout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(132, 132, 132)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(87, Short.MAX_VALUE)))
        );

        contenPanel.add(conten_tambahPanel, "card2");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setText("Id Supplier");

        id_supEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setText("Nama Supplier");

        namaSup_edit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel7.setText("Update At");

        update_atEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btn_simpanEdit.setBackground(new java.awt.Color(111, 59, 160));
        btn_simpanEdit.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btn_simpanEdit.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpanEdit.setText("Simpan");
        btn_simpanEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpanEditMouseClicked(evt);
            }
        });

        btn_cancelEdit.setBackground(new java.awt.Color(51, 45, 45));
        btn_cancelEdit.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btn_cancelEdit.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelEdit.setText("Cancel");
        btn_cancelEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cancelEditMouseClicked(evt);
            }
        });
        btn_cancelEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelEditActionPerformed(evt);
            }
        });

        btn_clearEdit.setBackground(new java.awt.Color(96, 96, 96));
        btn_clearEdit.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btn_clearEdit.setForeground(new java.awt.Color(255, 255, 255));
        btn_clearEdit.setText("Clear");
        btn_clearEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_clearEditMouseClicked(evt);
            }
        });
        btn_clearEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout conten_editPanelLayout = new javax.swing.GroupLayout(conten_editPanel);
        conten_editPanel.setLayout(conten_editPanelLayout);
        conten_editPanelLayout.setHorizontalGroup(
            conten_editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, conten_editPanelLayout.createSequentialGroup()
                .addGroup(conten_editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(conten_editPanelLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, conten_editPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nama_supLama)
                        .addGap(157, 157, 157)))
                .addGroup(conten_editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_clearEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
            .addGroup(conten_editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(conten_editPanelLayout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addGroup(conten_editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addGroup(conten_editPanelLayout.createSequentialGroup()
                            .addGroup(conten_editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(update_atEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(namaSup_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(id_supEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addGap(84, 84, 84)
                            .addComponent(btn_simpanEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(82, Short.MAX_VALUE)))
        );
        conten_editPanelLayout.setVerticalGroup(
            conten_editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, conten_editPanelLayout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addGroup(conten_editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, conten_editPanelLayout.createSequentialGroup()
                        .addComponent(nama_supLama)
                        .addGap(33, 33, 33)
                        .addComponent(btn_cancelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGap(27, 27, 27)
                .addComponent(btn_clearEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(conten_editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(conten_editPanelLayout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addComponent(jLabel5)
                    .addGap(12, 12, 12)
                    .addGroup(conten_editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(conten_editPanelLayout.createSequentialGroup()
                            .addComponent(id_supEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel6)
                            .addGap(12, 12, 12)
                            .addComponent(namaSup_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51)
                            .addComponent(update_atEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btn_simpanEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(82, Short.MAX_VALUE)))
        );

        contenPanel.add(conten_editPanel, "card2");

        label_Navigasi.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        label_Navigasi.setText("Supplier> Tambah Supplier");

        javax.swing.GroupLayout navigasi_panelLayout = new javax.swing.GroupLayout(navigasi_panel);
        navigasi_panel.setLayout(navigasi_panelLayout);
        navigasi_panelLayout.setHorizontalGroup(
            navigasi_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigasi_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_Navigasi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navigasi_panelLayout.setVerticalGroup(
            navigasi_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigasi_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_Navigasi, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(navigasi_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(navigasi_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setKodeSupplier(String kode){
        this.kode_supplier= kode;
    }
    public String getKodeSupplier(){
        return this.kode_supplier;
    }
    public void Action(String aksi){
        
        
        if(aksi.equals("add")){
            contenPanel.removeAll();
            contenPanel.add(conten_tambahPanel);
            contenPanel.repaint();
            contenPanel.revalidate();
           
            label_Navigasi.setText("Supplier > Tambah Supplier");
            this.setTitle("Tambah Supplier");
            this.setVisible(true);
            
            
            
        }else if(aksi.equals("edit")){
            contenPanel.removeAll();
            contenPanel.add(conten_editPanel);
            contenPanel.repaint();
            contenPanel.revalidate();
            label_Navigasi.setText("Supplier > Edit Supplier");
            this.setTitle("Edit Supplier");
            this.setVisible(true);
        }
        
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
         // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void btn_cancelEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelEditMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_cancelEditMouseClicked

    private void btn_cancelEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelEditActionPerformed

    private void btn_clearEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_clearEditActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
         // TODO add your handling code here:
         String nama_supplier= txt_nama_supplierAdd.getText().toString();
         String kode =txt_idSupplier.getText().toString();
         supplierService supplier = new supplierService();
         if(supplier.addSupplier(nama_supplier, kode, time)==true){
             supplier.showSupplier(Dashbord.table_supplier);
             this.dispose();
         }
        
         
         
         
    }//GEN-LAST:event_jButton1MouseClicked

    private void btn_simpanEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanEditMouseClicked
        // TODO add your handling code here:
        
        String kode = id_supEdit.getText().toString();
        String nama = namaSup_edit.getText().toString();
        
        supplierService suplier = new supplierService();
        if(!namaSup_edit.getText().toString().equals(nama_supLama.getText())){
            suplier.editSupplier(kode,nama , time, this);
            suplier.showSupplier(Dashbord.table_supplier);
        }else{
             JOptionPane.showMessageDialog(null, "Gagal Memperbarui ,Tidak ada perubahan pada Supplier" , "Terjadi Kesalahan", JOptionPane.ERROR_MESSAGE,eroricon );

        }
        
    }//GEN-LAST:event_btn_simpanEditMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
         // TODO add your handling code here:
         this.txt_nama_supplierAdd.setText("");
    }//GEN-LAST:event_jButton3MouseClicked

    private void btn_clearEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clearEditMouseClicked
         // TODO add your handling code here:
         this.namaSup_edit.setText("");
    }//GEN-LAST:event_btn_clearEditMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataTambahSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataTambahSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataTambahSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataTambahSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataTambahSupplier().setVisible(true);
            }
        });
    }
    
     public void tampilkanDataKeForm(String opsi , String kode_kat){
        DatabaseInterface dt = new Database();
        String kode="";
        String nama_kategori="";
        if(opsi.equals("edit")){
            
      
            String sql ="select kode_supplier , nama_supplier , update_at from supplier where kode_supplier = '"+kode_kat+"'";
            try(Connection con = dt.conectDatabase();
            Statement st = con.createStatement();
            ResultSet res = st.executeQuery(sql)){
            
            if(res.next()){
                kode =res.getString("kode_supplier");
                nama_kategori =res.getString("nama_supplier");
            
                id_supEdit.setText(kode_kat);
                namaSup_edit.setText(nama_kategori);
                update_atEdit.setText(time);
                nama_supLama.setText(nama_kategori);
                
            }
   
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Gagal Update Kategori"+e.getMessage(), "Terjadi Kesalahan", JOptionPane.INFORMATION_MESSAGE, eroricon);
        } 
            
            
            
            
            
        }
        
    }
    class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
        
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelEdit;
    private javax.swing.JButton btn_clearEdit;
    private javax.swing.JButton btn_simpanEdit;
    public static javax.swing.JPanel contenPanel;
    private javax.swing.JPanel conten_editPanel;
    private javax.swing.JPanel conten_tambahPanel;
    private javax.swing.JTextField id_supEdit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel label_Navigasi;
    private javax.swing.JTextField namaSup_edit;
    private javax.swing.JLabel nama_supLama;
    private javax.swing.JPanel navigasi_panel;
    private javax.swing.JTextField txt_createAtt;
    private javax.swing.JTextField txt_idSupplier;
    private javax.swing.JTextField txt_nama_supplierAdd;
    private javax.swing.JTextField update_atEdit;
    // End of variables declaration//GEN-END:variables
}
