/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import View.*;
import static View.Dashbord.table_barang;
import static View.DataBarangTambah.id_transaksi;
import static View.DataBarangTambah.txt_stok;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import service.OrderService;
import service.barangService;
import service.kategoriService;
import service.supplierService;

/**
 *
 * @author user
 */
public class KonfirmasiBayarUpdate extends javax.swing.JFrame {

   private String nama;
   private String kode;
   
   private String hargaJual;
   private String stok;
  // br.addBarang(nama_product, kode_product, hargaBeli, hargaJual,

    /** Creates new form KonfirmasiBayar */
    public KonfirmasiBayarUpdate() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        txt_bayar.requestFocus();
        label_hargaBeli.setVisible(false);
        label_hargaJual.setVisible(false);
        label_kategori.setVisible(false);
        label_kodeProduct.setVisible(false);
        label_namaProduct.setVisible(false);
        label_rusak.setVisible(false);
        label_stok.setVisible(false);
        label_supplier.setVisible(false);

    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new RoundedPanel(8, new Color(255, 255, 255));
        jLabel1 = new javax.swing.JLabel();
        label_supplier = new javax.swing.JLabel();
        label_kategori = new javax.swing.JLabel();
        label_stok = new javax.swing.JLabel();
        jPanel2 = new RoundedPanel(8, new Color(255, 255, 255));
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        id_transaksi = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_SubTotal = new javax.swing.JLabel();
        txt_bayar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_totalHarga = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_diskon = new javax.swing.JTextField();
        btn_bayar = new javax.swing.JButton();
        label_namaProduct = new javax.swing.JLabel();
        label_kodeProduct = new javax.swing.JLabel();
        label_hargaJual = new javax.swing.JLabel();
        label_rusak = new javax.swing.JLabel();
        label_hargaBeli = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(239, 240, 245));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(90, 90, 90));
        jLabel1.setText("Form Pembayaran Supplier");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(label_kategori)
                        .addGap(52, 52, 52)
                        .addComponent(label_supplier)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(label_stok)
                        .addGap(89, 89, 89))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(label_supplier)
                    .addComponent(label_kategori))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_stok))
        );

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(90, 90, 90));
        jLabel2.setText("ID TRANSAKSI");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(90, 90, 90));
        jLabel3.setText(":");

        id_transaksi.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        id_transaksi.setForeground(new java.awt.Color(90, 90, 90));
        id_transaksi.setText("TRJ2009001");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(90, 90, 90));
        jLabel5.setText("SUB TOTAL (Rp)");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(90, 90, 90));
        jLabel6.setText("DISKON (%)");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(90, 90, 90));
        jLabel7.setText(":");

        txt_SubTotal.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txt_SubTotal.setForeground(new java.awt.Color(90, 90, 90));
        txt_SubTotal.setText("1000.000.000");

        txt_bayar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txt_bayar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(90, 90, 90));
        jLabel9.setText("TOTAL HARGA (Rp)");

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(90, 90, 90));
        jLabel10.setText(":");

        txt_totalHarga.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txt_totalHarga.setForeground(new java.awt.Color(90, 90, 90));
        txt_totalHarga.setText("1000.000.000");

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(90, 90, 90));
        jLabel12.setText("BAYAR");

        txt_diskon.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txt_diskon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txt_diskon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_diskonKeyPressed(evt);
            }
        });

        btn_bayar.setBackground(new java.awt.Color(111, 59, 160));
        btn_bayar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btn_bayar.setForeground(new java.awt.Color(255, 255, 255));
        btn_bayar.setText("BAYAR");
        btn_bayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_bayarMouseClicked(evt);
            }
        });
        btn_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bayarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_diskon, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_totalHarga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txt_SubTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(id_transaksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(52, 52, 52)
                                                .addComponent(label_namaProduct)
                                                .addGap(18, 18, 18)
                                                .addComponent(label_kodeProduct))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(84, 84, 84)
                                                .addComponent(label_hargaBeli))))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(btn_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_hargaJual)
                    .addComponent(label_rusak))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_transaksi)
                            .addComponent(label_namaProduct)
                            .addComponent(label_kodeProduct))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_SubTotal)
                            .addComponent(label_hargaJual)
                            .addComponent(label_hargaBeli))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_diskon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_rusak))
                        .addGap(18, 18, 18)
                        .addComponent(txt_totalHarga)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txt_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btn_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_bayarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bayarMouseClicked
     
        String bayar =txt_bayar.getText();
       
        OrderService order = new OrderService();
      
        boolean isAdd=order.bayar(bayar.replaceAll("[^0-9]", ""), this , id_transaksi.getText().toString());
        
        barangService barang = new barangService();
        supplierService sup = new supplierService();
        kategoriService kat = new kategoriService();
       // barang.insertIdTransaksiBeli(id, suplier, tanggal, kategori, total ,);
        DataBarangTambah dt = new DataBarangTambah();
        String id_sup = sup.getKodeSupplier();
        String id =id_transaksi.getText().toString();
        System.out.println(id_sup);
        String tanggal =Timestamp.valueOf(LocalDateTime.now()).toString();
        String kode_kat =kat.getKodeKategori();
        String total =txt_totalHarga.getText();
       
       
    
      
        String nama_product=label_namaProduct.getText();
        String kode_product =label_kodeProduct.getText();
        String hargaBeli =label_hargaBeli.getText();
        String hargaJual =label_hargaJual.getText();
        String stok =label_stok.getText();
        String barangRusak =label_rusak.getText();
        System.out.println("nama"+nama_product);
        System.out.println("kode"+kode_product);
        System.out.println("beli"+hargaBeli);
        System.out.println("jual"+hargaJual);
        System.out.println("stok"+stok);
        System.out.println("rusak"+barangRusak);
        System.out.println();
        
        if(isAdd==true){
             String kembalianS=TransaksiBerhasilSupplier.txt_kembalian.getText().replaceAll(",", "");
             System.out.println("Sup"+this.getLabel_supplier());
             System.out.println("Kat"+this.getLabel_kategori());
             barang.insertIdTransaksiBeli(id, this.getLabel_supplier(), tanggal, this.getLabel_kategori(), total ,bayar.replaceAll("[^0-9]","") , kembalianS);
             String stokString = Restok.txt_tambahStok.getText();
             String stokLamaString = Restok.label_stok_lama.getText();
             int stokInt =Integer.parseInt(stokString);
             int stokLamaInt = Integer.parseInt(stokLamaString);
            
             boolean isSuces = barang.updateStok(kode_product, stokInt);
             if(isSuces==true){
                 System.out.println("ette");
             barang.insertDataTambahBanyakProduct(id, stokString ,kode_product);  
             barang.showBarang(Dashbord.table_barang);
        }
        }
       
       
    }//GEN-LAST:event_btn_bayarMouseClicked

    public void setLabelSupplier(String kode){
        this.label_supplier.setText(kode);
    }
    public void setLabelKategori(String kode){
        this.label_kategori.setText(kode);
    }
    public String getSupplier(){
        return label_supplier.getText().toString();
    }
    public String getKategori(){
        return this.label_kategori.getText().toString();
    }
    public void setLabel_stok(String stok) {
        this.label_stok.setText(stok);
    }

    public JLabel getLabel_hargaBeli() {
        return label_hargaBeli;
    }

    public void setLabel_hargaBeli(String label_hargaBeli) {
        this.label_hargaBeli.setText(label_hargaBeli);
    }

    public JLabel getLabel_hargaJual() {
        return label_hargaJual;
    }

    public void setLabel_hargaJual(String hargaJual) {
        this.label_hargaJual.setText(hargaJual);
    }

    public String getLabel_kategori() {
        return label_kategori.getText();
    }

    public void setLabel_kategori(String label_kategori) {
        this.label_kategori.setText(label_kategori);
    }

    public JLabel getLabel_kodeProduct() {
        return label_kodeProduct;
    }

    public void setLabel_kodeProduct(String kode) {
        this.label_kodeProduct.setText(kode);
    }

    public JLabel getLabel_namaProduct() {
        return label_namaProduct;
    }

    public void setLabel_namaProduct(String nama) {
        this.label_namaProduct.setText(nama);
    }

    public JLabel getLabel_rusak() {
        return label_rusak;
    }

    public void setLabel_rusak(String rusak) {
        this.label_rusak.setText(rusak);
    }

    public String getLabel_supplier() {
        return label_supplier.getText().toString();
    }

    public void setLabel_supplier(JLabel label_supplier) {
        this.label_supplier = label_supplier;
    }
 
    
    public void setKat(String id){
        this.label_kategori.setText(id);
    }
    public void setSupp(String id){
        this.label_supplier.setText(id);
    }
    public void setIdTransaksi(String id){
        this.id_transaksi.setText(id);
    }
//    public void action(){
//        this.setVisible(true);
//        this.setLocationRelativeTo(null);
//    }
    public void setSubTotal(String total){
        this.txt_SubTotal.setText(total);
        this.txt_totalHarga.setText(total);
    }
    public void setTotalResult(int total){
        String tmp = String.valueOf(total);
        this.txt_totalHarga.setText(tmp);
    }
  
    private void btn_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bayarActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_btn_bayarActionPerformed

    private void txt_diskonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_diskonKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()==evt.VK_ENTER){
            OrderService order = new OrderService();
            int total =order.hitungTotalHarga("update");
            
            this.txt_totalHarga.setText(String.valueOf(total));
        }
        
    }//GEN-LAST:event_txt_diskonKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonfirmasiBayarUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonfirmasiBayarUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonfirmasiBayarUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonfirmasiBayarUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonfirmasiBayarUpdate().setVisible(true);
            }
        });
    }

    void action() {
        
        this.setVisible(true);
        this.requestFocus();
    }
    
    
   

     class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bayar;
    public static javax.swing.JLabel id_transaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_hargaBeli;
    private javax.swing.JLabel label_hargaJual;
    private javax.swing.JLabel label_kategori;
    private javax.swing.JLabel label_kodeProduct;
    private javax.swing.JLabel label_namaProduct;
    private javax.swing.JLabel label_rusak;
    private javax.swing.JLabel label_stok;
    private javax.swing.JLabel label_supplier;
    public static javax.swing.JLabel txt_SubTotal;
    public static javax.swing.JTextField txt_bayar;
    public static javax.swing.JTextField txt_diskon;
    public static javax.swing.JLabel txt_totalHarga;
    // End of variables declaration//GEN-END:variables

}
